### ISSUE TITLE
Mongo Express Docker Extension

### ISSUE THREAD

**Issue by ajeetraina** [mongo-express/mongo-express#1037]
Being a frequent consumer of this tool, I always wanted to turn this project into an Extension. One obvious reason - I am always busy deploying microservices and Mongo is a part of my tech stack. Hence, to my interest, I built a Mongo Express Docker extension so that I can set up Mongo + Mongo Express at a much faster rate.

Here's the source code -  https://github.com/collabnix/mongoexpress-docker-extension

I have included the instructions to set it up. Give a try and let me know.
Learn More: https://docs.docker.com/desktop/extensions/

**Comment by shakaran** [comment]
@ajeetraina feel free to send a Pull Request modifying the README for include info about your extension. Thanks

**Comment by ajeetraina** [comment]
Sure @shakaran I will go ahead and raise the PR.

**Comment by shakaran** [comment]
Closing as resolved
