### ISSUE TITLE
Document detail fail with Binary ID

### ISSUE THREAD

**Issue by dariowrk** [mongo-express/mongo-express#1073]
Hey! 

I'm still having issues opening documents in detail-view which have _id as binary UUID.

Same as: [Document detail fail with Binary ID](https://github.com/mongo-express/mongo-express/issues/985)

On the GUI i get: Document not found!

The LOG just says:
GET /db/party/individualEntity/%22TUmQp0mK76ROCurJkoxrpg%3D%3D%22?subtype=3&skip=0 302 33.553 ms - 96

I am using a fresh build of the newest commit on master from this repository.

KR, Dario

**Comment by dariowrk** [comment]
If i look in a collection in the database our _id is displayed as follows (one for example): bEmV+PyOFqJjKfW9ZFBthw==

In the Document it should look like: _id: BinData(3, 'bEmV+PyOFqJjKfW9ZFBthw==')

The DetailView does not load and i get redirected to collection view with: Document not found!

**Comment by JohnDinhDev** [comment]
Was about to make an issue for the same exact thing
