### ISSUE TITLE
[Feature request] Print mongo-express version on startup

### ISSUE THREAD

**Issue by bluepuma77** [mongo-express/mongo-express#1107]
It would be great if mongo-express could print it's version upon startup.

Currently I only see this message in my Docker logs:
```
2023-01-18T20:09:10.860634196Z Welcome to mongo-express
2023-01-18T20:09:10.860892802Z ------------------------
2023-01-18T20:09:10.860901588Z
```

**Comment by akbhuker** [comment]
hi @shakaran would you please assign me

**Comment by rtritto** [comment]
Hi @akbhuker, I assigned to you

**Comment by akbhuker** [comment]
Hi @rtritto @shakaran I need to know where we stored the version of the mongo-express

**Comment by rtritto** [comment]
Version is in the _package.json_.
_package.json_ is already imported in [app.js](https://github.com/mongo-express/mongo-express/blob/master/app.js), where this feature should be do.

**Comment by akbhuker** [comment]
@rtritto how do I configure the production environment to run on my local machine

**Comment by rtritto** [comment]
Why do you want to start in prod mode?

You can start in dev mode with:
- `yarn`
- `yarn start-dev`

**Comment by akbhuker** [comment]
Hi @rtritto I opened a pull request #1125 can you please take a look
