### ISSUE TITLE
 Unsupported URL Type "patch:"

### ISSUE THREAD

**Issue by Gownowdupiechlupie** [mongo-express/mongo-express#1140]
debian@vps-4b709f6f:~$ sudo npm install -g mongo-express
npm WARN deprecated csurf@1.11.0: Please use another csrf package
npm WARN deprecated json2csv@5.0.7: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm WARN notsup Unsupported engine for mongo-express@1.0.1: wanted: {"node":"^14.17.0 || >=16.0.0 || >=18.0.0","npm":">=3.0.0"} (current: {"node":"8.17.0","npm":"6.13.4"})
npm WARN notsup Not compatible with your version of node/npm: mongo-express@1.0.1
npm WARN notsup Unsupported engine for busboy@1.6.0: wanted: {"node":">=10.16.0"} (current: {"node":"8.17.0","npm":"6.13.4"})
npm WARN notsup Not compatible with your version of node/npm: busboy@1.6.0
npm WARN notsup Unsupported engine for dotenv@16.0.3: wanted: {"node":">=12"} (current: {"node":"8.17.0","npm":"6.13.4"})
npm WARN notsup Not compatible with your version of node/npm: dotenv@16.0.3
npm WARN notsup Unsupported engine for express-fileupload@1.4.0: wanted: {"node":">=12.0.0"} (current: {"node":"8.17.0","npm":"6.13.4"})
npm WARN notsup Not compatible with your version of node/npm: express-fileupload@1.4.0
npm WARN notsup Unsupported engine for mongodb@4.14.0: wanted: {"node":">=12.9.0"} (current: {"node":"8.17.0","npm":"6.13.4"})
npm WARN notsup Not compatible with your version of node/npm: mongodb@4.14.0
npm WARN notsup Unsupported engine for free-swig@1.5.2: wanted: {"node":">=12.0.0"} (current: {"node":"8.17.0","npm":"6.13.4"})
npm WARN notsup Not compatible with your version of node/npm: free-swig@1.5.2
npm WARN notsup Unsupported engine for json2csv@5.0.7: wanted: {"node":">= 10","npm":">= 6.13.0"} (current: {"node":"8.17.0","npm":"6.13.4"})
npm WARN notsup Not compatible with your version of node/npm: json2csv@5.0.7

npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "patch:": patch:mongodb-query-parser@npm%3A2.4.6#~/.yarn/patches/mongodb-query-parser-npm-2.4.6-234abad2fc.patch

**Comment by itzwolf** [comment]
I am getting this as well on the mongodb-query-parser:

63 verbose stack Error: Unsupported URL Type "patch:": patch:mongodb-query-parser@npm%3A2.4.6#~/.yarn/patches/mongodb-query-parser-npm-2.4.6-234abad2fc.patch
63 verbose stack     at unsupportedURLType (/usr/lib/node_modules/npm/node_modules/npm-package-arg/lib/npa.js:327:15)
63 verbose stack     at fromURL (/usr/lib/node_modules/npm/node_modules/npm-package-arg/lib/npa.js:387:13)
63 verbose stack     at Function.resolve (/usr/lib/node_modules/npm/node_modules/npm-package-arg/lib/npa.js:83:12)
63 verbose stack     at /usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1032:38
63 verbose stack     at Array.map (<anonymous>)
63 verbose stack     at visit (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1031:56)
63 verbose stack     at visitNode (/usr/lib/node_modules/npm/node_modules/treeverse/lib/depth-descent.js:58:25)
63 verbose stack     at next (/usr/lib/node_modules/npm/node_modules/treeverse/lib/depth-descent.js:44:19)
63 verbose stack     at depth (/usr/lib/node_modules/npm/node_modules/treeverse/lib/depth-descent.js:83:10)
63 verbose stack     at depth (/usr/lib/node_modules/npm/node_modules/treeverse/lib/depth.js:27:12)

**Comment by jthantranon** [comment]
me 3

**Comment by rtritto** [comment]
Close as duplicate of #1135
