### ISSUE TITLE
Unsupported URL Type "patch:": patch:renderjson@npm%3A1.4.0#~/.yarn/patches/renderjson-npm-1.4.0-b198ae5f7e.patch

### ISSUE THREAD

**Issue by itzwolf** [mongo-express/mongo-express#1143]
Attempts to build the latest master results in a unsupported URL type error. This is on npm 9.5.0 & 9.5.1. This same patch error was affecting the patch for mongodb-query-parser before the most recent commit related to issue #1136.

$ npm i mongo-express@git+https://github.com/mongo-express/mongo-express.git#master
npm WARN deprecated csurf@1.11.0: Please use another csrf package
npm WARN deprecated json2csv@5.0.7: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm ERR! code 1
npm ERR! git dep preparation failed
npm ERR! command /usr/bin/node /usr/lib/node_modules/npm/bin/npm-cli.js install --force --cache=/home/pi/.npm --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit --include=dev --include=peer --include=optional --no-package-lock-only --no-dry-run
npm ERR! npm WARN using --force Recommended protections disabled.
npm ERR! npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! npm ERR! Unsupported URL Type "patch:": patch:renderjson@npm%3A1.4.0#~/.yarn/patches/renderjson-npm-1.4.0-b198ae5f7e.patch

Captured from error log:

144 verbose stack Error: Unsupported URL Type "patch:": patch:renderjson@npm%3A1.4.0#~/.yarn/patches/renderjson-npm-1.4.0-b198ae5f7e.patch
144 verbose stack     at unsupportedURLType (/usr/lib/node_modules/npm/node_modules/npm-package-arg/lib/npa.js:327:15)
144 verbose stack     at fromURL (/usr/lib/node_modules/npm/node_modules/npm-package-arg/lib/npa.js:387:13)
144 verbose stack     at Function.resolve (/usr/lib/node_modules/npm/node_modules/npm-package-arg/lib/npa.js:83:12)
144 verbose stack     at [nodeFromEdge] (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1058:22)
144 verbose stack     at [buildDepStep] (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:929:36)
144 verbose stack     at async Arborist.buildIdealTree (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:207:7)
144 verbose stack     at async Promise.all (index 1)
144 verbose stack     at async Arborist.reify (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:159:5)
144 verbose stack     at async Install.exec (/usr/lib/node_modules/npm/lib/commands/install.js:146:5)
144 verbose stack     at async module.exports (/usr/lib/node_modules/npm/lib/cli.js:134:5)

**Comment by rtritto** [comment]
Duplicate #1135

**Comment by itzwolf** [comment]
This issue is specifically related to the patch for renderjson and not mongodb-query-parser which was fixed. I don't really see this as a duplicate to #1135 or resolved in #1136.

**Comment by rtritto** [comment]
Sorry, reopened

**Comment by tarkh** [comment]
Having same issue. Can't install mongo-express at all. After running `npm install -g mongo-express` getting this error:
```
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "patch:": patch:mongodb-query-parser@npm%3A2.4.6#~/.yarn/patches/mongodb-query-parser-npm-2.4.6-234abad2fc.patch

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/www/.npm/_logs/2023-03-13T16_56_31_476Z-debug-0.log
```
Any solution?

**Comment by rtritto** [comment]
As alternative you can use `yarn`:
`yarn global add mongo-express`

**Comment by rtritto** [comment]
You should first build and then start.

**Comment by AnoopJoseC** [comment]
s# npm install mongo-express --ignore-scripts && npm install
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "patch:": patch:mongodb-query-parser@npm%3A2.4.6#~/.yarn/patches/mongodb-query-parser-npm-2.4.6-234abad2fc.patch


Still getting this error. Any solution?

**Comment by tranduyhung** [comment]
I get this `EUNSUPPORTEDPROTOCOL` error when installing globally and non-globally. `npm@8.19.3`, `node@v16.19.0`.

**Comment by retropele** [comment]
Same as the others, when I installed yarn as a workaround I still get this error:

```
Error: ENOENT: no such file or directory, open './build-assets.json'
    at Object.openSync (node:fs:581:18)
    at Object.readFileSync (node:fs:457:35)
    at file:///home/ele/.config/yarn/global/node_modules/mongo-express/lib/middleware.js:9:30
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:113:12) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: './build-assets.json'
}
```

**Comment by stefexec** [comment]
npm i -g mongo-express                                   
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "patch:": patch:mongodb-query-parser@npm%3A2.4.6#~/.yarn/patches/mongodb-query-parser-npm-2.4.6-234abad2fc.patch

**Comment by gokulraja2787** [comment]
I get same error. With node 20:

npm i mongo-express
npm error code EUNSUPPORTEDPROTOCOL
npm error Unsupported URL Type "patch:": patch:mongodb-query-parser@npm%3A2.4.6#~/.yarn/patches/mongodb-query-parser-npm-2.4.6-234abad2fc.patch

**Comment by terrynguyen255** [comment]
Encountering sane issue.
`npm i mongo-express@1.0.0` works
