### ISSUE TITLE
UhandledPromiseRejectionWarning: MongoNetworkError: failed to connect to server [mongodb:27017] on first connect [MongoError: Authentication failed.

### ISSUE THREAD

**Issue by elias-soykat** [mongo-express/mongo-express#1186]
When I try to run `docker-compose up --build` command I facing this issue.

Bellow I share my docker-compose file

<img width="1282" alt="Screenshot 2023-04-19 at 6 21 27 PM" src="https://user-images.githubusercontent.com/76895393/233073736-7d089167-40b7-4f4f-88d2-5cb7bea78cc8.png">

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server
    depends_on:
      - mongodb
    env_file: .env
    ports:
      - 4000:4000
    command: npm run dev
    volumes:
      - app-data:/app
      - ./src:/app/src
      - /app/node_modules

    networks:
      - mongo-network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: ticketify
    ports:
      - 27017:27017
    volumes:
      - db-data:/data/db
    networks:
      - mongo-network

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    depends_on:
      - mongodb
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_AUTH_USERNAME: root
      ME_CONFIG_MONGODB_AUTH_PASSWORD: example
      ME_CONFIG_MONGODB_AUTH_DATABASE: ticketify
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongodb:27017
    networks:
      - mongo-network

networks:
  mongo-network:
    driver: bridge

volumes:
  app-data:
  db-data:

**Comment by walosha** [comment]
same here

**Comment by walosha** [comment]
> mongodb

Use the mongo  service name instead of mongo

**Comment by WebOrganics** [comment]
I have this exactly same issue, its effecting all stacks with the mongo express image 

"(node:7) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code."

I now have to remove/disable all instances of mongo-express:latest

**Comment by elias-soykat** [comment]
> I have this exactly same issue, its effecting all stacks with the mongo express image
> 
> "(node:7) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code."
> 
> I now have to remove/disable all instances of mongo-express:latest

you can try below way. i share my `docker-compose.yml` in below link

https://github.com/elias-soykat/ticketify/blob/master/docker-compose.yml
