### ISSUE TITLE
Secret option required for sessions

### ISSUE THREAD

**Issue by tuanho091** [mongo-express/mongo-express#1211]
I deploy mongo express to k8s with config:
![image](https://github.com/mongo-express/mongo-express/assets/76595793/7cda2ff9-4eea-4190-ab04-0e9097a1ddf4)

But after login, server response 500. 
![image](https://github.com/mongo-express/mongo-express/assets/76595793/acbe75bf-5225-41bf-9bde-40e3f3e7ea64)

Logs server:
![image](https://github.com/mongo-express/mongo-express/assets/76595793/9739a553-cb59-4497-9eb0-7dc9dc6a6342)

Values of variable ME_CONFIG_SITE_SESSIONSECRET and ME_CONFIG_SITE_COOKIESECRET, i use default value. This is "sessionsecret" and "cookiesecret"

**Comment by mingfang** [comment]
I'm seeing the same problem. what was the solution?
