### ISSUE TITLE
Slow pagination

### ISSUE THREAD

**Issue by miky4u2** [mongo-express/mongo-express#1233]
I have a collection with 12 million documents and an index on _id .  Clicking on the collection to get the first 10 records takes several minutes. It also takes minutes to change the page. There is also the mention of 'delete12564932 retrieved records'.  On the other hand, using Mongosh and a query using a combination of sort(), skip() and limit(10) , returns 10 documents instantly and paginating through the 12M records is instant.  It seems that mongo-express retrieves the whole collection of every page.
Mongo 6.0.7  
mongo-express container from code from a few days ago.

**Comment by rtritto** [comment]
Related discussion: https://github.com/mongo-express/mongo-express/discussions/1091

Did you try latest code on master?

**Comment by MPoppinga** [comment]
Facing the same problem on large collections. I'm using the latest master, 24dcc13.

Further, setting ME_CONFIG_DOCUMENTS_PER_PAGE does change the value of the skip parameter, but regardless of its value always 100 results are displayed. It looks like that in this case the limit is not run in the database and it always does a COLLSCAN.

I think #1518 is related.
