### ISSUE TITLE
cannot be moved on to the next page

### ISSUE THREAD

**Issue by Caffeine21** [mongo-express/mongo-express#1312]
We found that the page move URL contains the variable runAggregate=false.
If this variable is included, the URL will not work.
I'm using a docker. Is there a way to solve this problem?

**Comment by rtritto** [comment]
Please can you add the reproduction steps and the error log?

**Comment by Caffeine21** [comment]
![image](https://github.com/mongo-express/mongo-express/assets/64478772/d2d80779-4f8b-4aa2-81d5-efac6a615821)

**Comment by Caffeine21** [comment]
The conditions for the reenactment are simple. Just press the move button

![image](https://github.com/mongo-express/mongo-express/assets/64478772/0a6c739a-a3f5-42ef-847e-81aabd235377)

**Comment by juan-leon** [comment]
I have same problem (my workaround is to edit the URL and add `&skip=30`, so I can avoid the `runAggregate=false` and 'projection=' in generated url)

These are the logs of the mongo-express docker image (I am using `mongo-express:latest` from 4 days ago, `a776ee465303`)

```
mongo-express  | MongoInvalidArgumentError: Argument "pipeline" must be an array of aggregation stages
mongo-express  |     at Collection.aggregate (/node_modules/mongodb/lib/collection.js:368:19)
mongo-express  |     at exp.viewCollection (/node_modules/mongo-express/lib/routes/collection.js:167:26)
mongo-express  |     at Layer.handle [as handle_request] (/node_modules/express/lib/router/layer.js:95:5)
mongo-express  |     at next (/node_modules/express/lib/router/route.js:144:13)
mongo-express  |     at mongoMiddleware (/node_modules/mongo-express/lib/router.js:260:5)
mongo-express  |     at Layer.handle [as handle_request] (/node_modules/express/lib/router/layer.js:95:5)
mongo-express  |     at next (/node_modules/express/lib/router/route.js:144:13)
mongo-express  |     at Route.dispatch (/node_modules/express/lib/router/route.js:114:3)
mongo-express  |     at Layer.handle [as handle_request] (/node_modules/express/lib/router/layer.js:95:5)
mongo-express  |     at /node_modules/express/lib/router/index.js:284:15 {
mongo-express  |   [Symbol(errorLabels)]: Set(0) {}
mongo-express  | }
mongo-express  | GET /db/ikb/interactions?skip=10&key=&value=&type=S&query=&projection=&runAggregate=false&sort[date]=-1 302 4.284 ms - 266
```

**Comment by juan-leon** [comment]
> Try to remove `mongo-express` image and then pull a new one.

I did that and problem is not fixed.

From `docker image inspect mongo-express` I can see 2 things:

This will help you to identify the image

```
"Id": "sha256:a239c27c8e22fae6501db32bde19fa3133b54189cacd9f4779753234dfcc1f8d",
...
"Created": "2023-10-16T16:59:03.180212847Z",
```

However, despite the image being created yesterday, I can see this also

```
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                ...
                "MONGO_EXPRESS_VERSION=1.0.0"
            ],
```

I would have expected 1.0.1 or 1.0.2 (from the comments on other issues)
