### ISSUE TITLE
Impossible to install MongoDB (used all ways possible to do)

### ISSUE THREAD

**Issue by astrobob** [mongo-express/mongo-express#1317]
Hello,

First thank you for this project I used few years ago and was fine.

I tried to install it on my new environment with v18.18.2 and monDB 6.0.11 but either way it doesn't work.

1) First try with `npm i -g mongo-express@git+https://github.com/mongo-express/mongo-express.git#master` on your documentation. I get:

```
npm WARN deprecated csurf@1.11.0: Please use another csrf package
npm ERR! code 236
npm ERR! git dep preparation failed
npm ERR! command /home/nfs-clients/fc40d1f3e944059a40ea39dc9c6f5aa7/.nvm/versions/node/v18.18.2/bin/node /home/nfs-clients/fc40d1f3e944059a40ea39dc9c6f5aa7/.nvm/versions/node/v18.18.2/lib/node_modules/npm/bin/npm-cli.js install --force --cache=/home/clients/fc40d1f3e944059a40ea39dc9c6f5aa7/.npm --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit --include=dev --include=peer --include=optional --no-package-lock-only --no-dry-run
npm ERR! npm WARN using --force Recommended protections disabled.
npm ERR! npm ERR! code ENOTDIR
npm ERR! npm ERR! syscall rename
npm ERR! npm ERR! path /home/nfs-clients/fc40d1f3e944059a40ea39dc9c6f5aa7/.nvm/versions/node/v18.18.2/lib/node_modules/mongo-express
npm ERR! npm ERR! dest /home/nfs-clients/fc40d1f3e944059a40ea39dc9c6f5aa7/.nvm/versions/node/v18.18.2/lib/node_modules/.mongo-express-kwdHkU3S
npm ERR! npm ERR! errno -20
npm ERR! npm ERR! ENOTDIR: not a directory, rename '/home/nfs-clients/fc40d1f3e944059a40ea39dc9c6f5aa7/.nvm/versions/node/v18.18.2/lib/node_modules/mongo-express' -> '/home/nfs-clients/fc40d1f3e944059a40ea39dc9c6f5aa7/.nvm/versions/node/v18.18.2/lib/node_modules/.mongo-express-kwdHkU3S'
npm ERR! 
npm ERR! npm ERR! A complete log of this run can be found in: /home/clients/fc40d1f3e944059a40ea39dc9c6f5aa7/.npm/_logs/2023-10-20T11_42_33_227Z-debug-0.log

npm ERR! A complete log of this run can be found in: /home/clients/fc40d1f3e944059a40ea39dc9c6f5aa7/.npm/_logs/2023-10-20T11_42_17_875Z-debug-0.log
```

2) Second try still on your documentation:` npm install -g mongo-express`, I get:

```
npm ERR! Unsupported URL Type "patch:": patch:mongodb-query-parser@npm%3A2.4.6#~/.yarn/patches/mongodb-query-parser-npm-2.4.6-234abad2fc.patch

npm ERR! A complete log of this run can be found in: /home/clients/fc40d1f3e944059a40ea39dc9c6f5aa7/.npm/_logs/2023-10-20T11_48_36_908Z-debug-0.log

```

3) Finally by cloning locally the repo with `git clone https://github.com/mongo-express/mongo-express.git` and then `npm run build`: 

```
> mongo-express@1.0.0 build
> NODE_ENV=production webpack

sh: 1: webpack: Permission denied
```

Could you please update the documentation to tell if there is any environment contraints (version of nodejs or mongodb or other libraries to install first) or update the documentation to install it.

Thank you in advance

**Comment by kwynncom** [comment]
I got the same error, but going back a few versions worked for me:

npm install mongo-express@v1.0.0
cd node_modules/mongo-express
node app.js

Result:
No custom config.js found, loading config.default.js
Welcome to mongo-express
------------------------
[...]
Mongo Express server listening at http://localhost:8081

**Comment by rtritto** [comment]
Duplicate of #1362
Fixed in https://github.com/mongo-express/mongo-express/pull/1255
Npm pacakge needs to be updated.
Until that, you can instead use main branch.
