### ISSUE TITLE
can not go to the next page (pagination)

### ISSUE THREAD

**Issue by eviltik** [mongo-express/mongo-express#1332]
Hi

When clicking on page 2 on a collection, i stay on page 1 (i can see the page is reloading, but without a GET param for pagination). I'm using nginx as a reverse proxy in front of mongodb-express docker (without cache). I forced "disable cache" in chrome console without luck.

MongoDB Version: 6.0.11
Node version: 18.18.2
Platform: docker

I can't see/fetch mongodb-express version, but i think it's the latest (i'm using "FROM mongo-express" in the docker file)

Any idea ? Thank you.

**Comment by dblum-analog** [comment]
Looks like the [issue is being tracked here](https://github.com/mongo-express/mongo-express-docker/issues/104)

**Comment by nofacer** [comment]
same

**Comment by eggcho** [comment]
The same here. Latest version has pagination issue! Version [1.0.0-alpha.4] work as expected.

**Comment by eviltik** [comment]
@rtritto hi, this tickets is 2 months old, mongodb-express is not usable, this is critical. Can the dev team handle this ? thank yuo

**Comment by rtritto** [comment]
Docker image get the code from _npm_.
Latest Docker image use npm v1.0.0 (ENV MONGO_EXPRESS_VERSION=1.0.0 in Dockerfile).
@BlackthornYugen please can you update (publish) a new Docker image?

**Comment by BlackthornYugen** [comment]
> Docker image get the code from _npm_. Latest Docker image use npm v1.0.0 (ENV MONGO_EXPRESS_VERSION=1.0.0 in Dockerfile). @BlackthornYugen please can you update (publish) a new Docker image?

As I've said in other threads I've not been able to do that. There was a problem with the yarn build.

**Comment by BlackthornYugen** [comment]
Sorry for the wait -- we have made progress. 1.02 will be available from dockerhub once https://github.com/docker-library/official-images/pull/15991 is merged.

**Comment by eviltik** [comment]
Everything is OK now, big thanks team  :100:
