### ISSUE TITLE
npm install -g mongo-express error for linux arm64

### ISSUE THREAD

**Issue by alfirus** [mongo-express/mongo-express#1362]
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "patch:": patch:mongodb-query-parser@npm%3A2.4.6#~/.yarn/patches/mongodb-query-parser-npm-2.4.6-234abad2fc.patch

**Comment by notchris** [comment]
Had same issue, needed to install yarn

**Comment by rtritto** [comment]
Fixed in #1255
Npm dependency or Docker image need to be updated
Until that, you can instead use main branch
