### ISSUE TITLE
Pagination not limited

### ISSUE THREAD

**Issue by rtritto** [mongo-express/mongo-express#1395]
After #1394, there isn't any pagination limit.

## Previous

Pagination limit is 5 pages.
Go to first/last page button.

<img width="866" alt="image" src="https://github.com/mongo-express/mongo-express/assets/40242971/87918ad5-3d6f-4fc9-b9e6-7f4de7845f4f">

## Current

<img width="837" alt="image" src="https://github.com/mongo-express/mongo-express/assets/40242971/0c20bd6c-7582-4632-878d-0884ed797251">

**Comment by rtritto** [comment]
Should we update and use https://github.com/rtritto/bootstrap-paginator/tree/develop?

**Comment by rtritto** [comment]
FYI @GhassenRjab

**Comment by GhassenRjab** [comment]
Nice catch @rtritto! I'll see what I can do

**Comment by rtritto** [comment]
@GhassenRjab I did #1396, please can you check?
