### ISSUE TITLE
Fix responsive layout

### ISSUE THREAD

**Issue by rtritto** [mongo-express/mongo-express#1459]
Fix layout (responsive?):
- yellow buttons are overlapped
- "test" text is over yellow button
- delete button io out of the box

<img width="559" alt="image" src="https://github.com/mongo-express/mongo-express/assets/40242971/5195964a-7eb8-4388-9bc0-9ae2779f9dd7">

**Comment by xTudoS** [comment]
definitely a responsiveness issue. could you see if in this PR it looks ok? https://github.com/mongo-express/mongo-express/pull/1456

**Comment by xTudoS** [comment]
@rtritto did you see others pages with this problems? I could see just the collections list page

**Comment by rtritto** [comment]
@xTudoS on resizing, bottom of "Find" button is below the "Query" and "Projection" textarea.

<img width="535" alt="image" src="https://github.com/mongo-express/mongo-express/assets/40242971/2bd310dd-fdc0-42c7-834a-b6d250f16afa">
