### ISSUE TITLE
MONGO-EXPRESS

### ISSUE THREAD

**Issue by Shireen305** [mongo-express/mongo-express#1494]
$ kubectl logs mongo-express-859f75dd4f-mxq2j
Waiting for mongo:27017...
/docker-entrypoint.sh: line 15: mongo: Name does not resolve
/docker-entrypoint.sh: line 15: /dev/tcp/mongo/27017: Invalid argument
Tue Apr  2 03:34:19 UTC 2024 retrying to connect to mongo:27017 (2/10)
/docker-entrypoint.sh: line 15: mongo: Name does not resolve
/docker-entrypoint.sh: line 15: /dev/tcp/mongo/27017: Invalid argument
Tue Apr  2 03:34:20 UTC 2024 retrying to connect to mongo:27017 (3/10)
/docker-entrypoint.sh: line 15: mongo: Name does not resolve
/docker-entrypoint.sh: line 15: /dev/tcp/mongo/27017: Invalid argument
Tue Apr  2 03:34:21 UTC 2024 retrying to connect to mongo:27017 (4/10)
/docker-entrypoint.sh: line 15: mongo: Name does not resolve
/docker-entrypoint.sh: line 15: /dev/tcp/mongo/27017: Invalid argument
Tue Apr  2 03:34:22 UTC 2024 retrying to connect to mongo:27017 (5/10)
/docker-entrypoint.sh: line 15: mongo: Name does not resolve
/docker-entrypoint.sh: line 15: /dev/tcp/mongo/27017: Invalid argument
Tue Apr  2 03:34:23 UTC 2024 retrying to connect to mongo:27017 (6/10)
/docker-entrypoint.sh: line 15: mongo: Name does not resolve
/docker-entrypoint.sh: line 15: /dev/tcp/mongo/27017: Invalid argument
Tue Apr  2 03:34:24 UTC 2024 retrying to connect to mongo:27017 (7/10)
/docker-entrypoint.sh: line 15: mongo: Name does not resolve
/docker-entrypoint.sh: line 15: /dev/tcp/mongo/27017: Invalid argument
Tue Apr  2 03:34:25 UTC 2024 retrying to connect to mongo:27017 (8/10)
/docker-entrypoint.sh: line 15: mongo: Name does not resolve
/docker-entrypoint.sh: line 15: /dev/tcp/mongo/27017: Invalid argument
Tue Apr  2 03:34:26 UTC 2024 retrying to connect to mongo:27017 (9/10)
/docker-entrypoint.sh: line 15: mongo: Name does not resolve
/docker-entrypoint.sh: line 15: /dev/tcp/mongo/27017: Invalid argument
Tue Apr  2 03:34:27 UTC 2024 retrying to connect to mongo:27017 (10/10)
/docker-entrypoint.sh: line 15: mongo: Name does not resolve
/docker-entrypoint.sh: line 15: /dev/tcp/mongo/27017: Invalid argument
No custom config.js found, loading config.default.js
Welcome to mongo-express 1.0.2
------------------------

Mongo Express server listening at http://0.0.0.0:8081
Server is open to allow connections from anyone (0.0.0.0)
basicAuth credentials are "admin:pass", it is recommended you change this in your config.js!
this is the error I'm getting.I can't figure out what it is?

mongo-express code
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
  labels:
    app: mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
      - name: mongo-express
        image: mongo-express
        ports:
        - containerPort: 8081
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-username
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-password
        - name: ME_CONFIG_MONGODB_SERVER
          valueFrom:
            configMapKeyRef:
              name: mongodb-configmap
              key: database_url
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
spec:
  selector:
      app: mongo-express
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30000

mongo.yml code
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongo
        image: mongo
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-password
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017

**Comment by Shireen305** [comment]
Please help me out with this

**Comment by xTudoS** [comment]
> Please help me out with this

are you sure the mongo instance is running under "mongo" name ? 
by your provided config it seems to be "mongodb-service" instead of "mongo"

**Comment by Shireen305** [comment]
Yes strangely it is even though my config map specifies mongodb-service

**Comment by xTudoS** [comment]
> Environment: ME_CONFIG_MONGODB_ADMINUSERNAME: <set to the key 'mongo-root-username' in secret 'mongodb-secret'> Optional: false ME_CONFIG_MONGODB_ADMINPASSWORD: <set to the key 'mongo-root-password' in secret 'mongodb-secret'> Optional: false ME_CONFIG_MONGODB_SERVER: <set to the key 'database_url' of config map 'mongodb-configmap'> Optional: false I can see this when I do describe for the pod but when I run the logs it shows that!

inside others pods, how do you connect to mongodb server in others pods? using "mongodb" or other name?
in your configuration, did you config ME_CONFIG_MONGODB_SERVER ? I think mongo-express is trying to use the default for ME_CONFIG_MONGODB_SERVER (mongodb) but you had named it with other name, so you have to pass this config with the correct one

**Comment by Shireen305** [comment]
I did  below is my config map
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-configmap
data:
  database_url: mongodb-service
  

I also executed this command and it shows having the right url
kubectl exec -it mongo-express-{podname} -- /bin/sh -c 'echo $ME_CONFIG_MONGODB_SERVER'
mongodb-service

I really can't figure it out

**Comment by xTudoS** [comment]
same error " mongo: Name does not resolve"?

could you try this? https://github.com/mongo-express/mongo-express-docker/issues/120#issuecomment-1956048652

**Comment by Shireen305** [comment]
Okay this atleast is not picking the wrong service giving me a new error but I'll take that :) Thanks  a lot!

**Comment by Shireen305** [comment]
---
Mongo Express
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
  labels:
    app: mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
      - name: mongo-express
        image: mongo-express
        ports:
        - containerPort: 8081
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-username
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom: 
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-password
        - name: ME_CONFIG_MONGODB_URL
          valueFrom: 
            configMapKeyRef:
              name: mongodb-configmap
              key: database_url

ConfigMap
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-configmap
data:
  database_url: "mongodb://mongodb-service:27017"
  
getting error
/app/node_modules/mongodb/lib/cmap/connection.js:227
                    callback(new error_1.MongoServerError(document));
                             ^

MongoServerError: Command listDatabases requires authentication
    at Connection.onMessage (/app/node_modules/mongodb/lib/cmap/connection.js:227:30)
    at MessageStream.<anonymous> (/app/node_modules/mongodb/lib/cmap/connection.js:60:60)
    at MessageStream.emit (node:events:517:28)
    at processIncomingData (/app/node_modules/mongodb/lib/cmap/message_stream.js:125:16)
    at MessageStream._write (/app/node_modules/mongodb/lib/cmap/message_stream.js:33:9)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at Writable.write (node:internal/streams/writable:337:10)
    at Socket.ondata (node:internal/streams/readable:809:22)
    at Socket.emit (node:events:517:28) {
  ok: 0,
  code: 13,
  codeName: 'Unauthorized',
  [Symbol(errorLabels)]: Set(0) {}
}

Node.js v18.20.0
I see this issue but most people have not used secret and configmap and just exposed the username and password when I use secret and configmap this throws the above error

**Comment by xTudoS** [comment]
I'm pretty sure you will have to pass the username/password with ME_CONFIG_MONGODB_URL
 like: mongodb://username:password@localhost:27017/?authSource=admin'

mongo-express has a view to ask for them if not provided, but is not in the official docker image

**Comment by Shireen305** [comment]
But I was wondering about security then ..Don't we have security files for a reason this may I am exposing username and password

**Comment by xTudoS** [comment]
What if you put ME_CONFIG_MONGODB_URL in the secret?

**Comment by Shireen305** [comment]
but in secret we encrypt the key right and not just put it in plaintext ,If I'm not mistaken

**Comment by xTudoS** [comment]
if isn't a way to decrypt and pass the key before send to mongo-express ENV vars, so in this moment plaintext is the only way. This can be convert to a request feature and be available in next versions

**Comment by Shireen305** [comment]
Strangely not working in plaintext also

**Comment by xTudoS** [comment]
what is the error?

**Comment by Shireen305** [comment]
Authentication failed

**Comment by Shireen305** [comment]
Didn’t change anything no username or password too

**Comment by xTudoS** [comment]
Authentication failed means the is something wrong with your provided connection url. Check if you had passed all required params (Ex. authSource, etc)

**Comment by Shireen305** [comment]
yes all parameters that are needed is there
database_url: ***@***.***:27017

**Comment by xTudoS** [comment]
where is the authSource part?

**Comment by Shireen305** [comment]
This is what is given for a connection string...I can't find anything else

**Comment by xTudoS** [comment]
try put ?authSource=admin and check if it works 
like
mongodb://username:password@localhost:27017/?authSource=admin

this is not more a mongo-express related thing 
so if you don't mind I can continue to try to help you via email: x2do@protonmail.com

**Comment by Shireen305** [comment]
This problem has been thanks to @xTudoS 

Mongo_express has deprecated the Server env variable

You need to use ME_CONFIG_MONGODB_URL
Attcaching the code so that nobody struggles the way i did

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
  labels:
    app: mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
      - name: mongo-express
        image: mongo-express
        ports:
        - containerPort: 8081
        env:
        - name: ME_CONFIG_MONGODB_URL
          value: "mongodb://admin:pass@mongodb-service:27017/"
        - name: ME_CONFIG_MONGODB_AUTH_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-username
        - name: ME_CONFIG_MONGODB_AUTH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-password
        - name: ME_CONFIG_BASICAUTH_USERNAME
          value: "admin"
        - name: ME_CONFIG_BASICAUTH_PASSWORD
          value: "pass"

**Comment by ddodoo** [comment]
Hello @Shireen305 

I found a response that worked for me here

https://github.com/weechien/mongo-express-k8s/issues/1#issuecomment-2391915357

**Comment by farazshaikh581** [comment]
Hello @Shireen305  and @ddodoo , the both didn't work with me.

**Comment by farazshaikh581** [comment]
Hello @Shireen305 , my problem isn't solved yet by using all the possible solutions I saw online. Can you please help me?

**Comment by xTudoS** [comment]
> Hello [@Shireen305](https://github.com/Shireen305) , my problem isn't solved yet by using all the possible solutions I saw online. Can you please help me?

what is your problem?
