### ISSUE TITLE
Installation issue on amazon linux 2023

### ISSUE THREAD

**Issue by saikrishna1488** [mongo-express/mongo-express#1543]
I tried to install it in amazon linux 2023 and i am facing lot of dependency inssues at start itself after running the command
"npm i mongo-express@git+https://github.com/mongo-express/mongo-express.git#master" not able move forward. The documentation need to be better it is very hard for beginners.

**Comment by xTudoS** [comment]
would you please provide more information? Like the nodejs / npm version you are using?

**Comment by rtritto** [comment]
@saikrishna1488 please can you test again?

I updated the script in the _README_:
`npm i mongo-express@github:mongo-express/mongo-express`
