### ISSUE TITLE
Fix colors in document editing

### ISSUE THREAD

**Issue by rtritto** [mongo-express/mongo-express#1558]
Fix colors for types (ObjectId, UUID, ISODate etc) and values (Number etc).

### Actual Firefox (should be OK but _from_ and _to_ fields have same type but different color)
![image](https://github.com/mongo-express/mongo-express/assets/40242971/8ddf3b5e-55a2-48fe-a3c6-945007516dc9)

### Actual Chrome
The color is only white
<img width="371" alt="image" src="https://github.com/mongo-express/mongo-express/assets/40242971/a0e4dfd2-07ed-4a0e-bd54-46916cf9ee4e">

### Expected (previous)
<img width="356" alt="image" src="https://github.com/mongo-express/mongo-express/assets/40242971/59261a2a-adb4-4b16-bec7-4ea54b70890b">

**Comment by codeshaine** [comment]
Hii, I think i figured out why this is happening , well the reason is the editor is built using codemirror package and  it is using javascript syntax highlight . can i try to solve this issue ?
