### ISSUE TITLE
Collections export do not respect projections

### ISSUE THREAD

**Issue by GerkinDev** [mongo-express/mongo-express#1591]
Hi,

I'm trying to use this package to give to some collaborators a simple cURL command they can use to fetch users, by only cherry-picking certain fields. The query looks like this:

`http://127.0.0.1:8081/db/myDB/expArr/users?projection={name: 1, username: 1, email: 1}`

But it seems that the export is not respecting the projection. I've checked out the source code, and at a first glance I don't see any passing of the `projection` query parameter to the export functions. But according to changes in #388 it was present previously.

I see that effbbe6f917db999f66972e1c50767e863387a1d removed the projection parameter, but I feel like it is missing from the `queryOptions` object

Am I missing something, or is it a regression ?

**Comment by rtritto** [comment]
Current code of master branch use `_getQuery` function to create query from request:
- exportCollection:
  https://github.com/mongo-express/mongo-express/blob/89ae24008e9405c5ef2e04d0457d54cae1c3a263/lib/routes/collection.js#L265
- exportColArray:
  https://github.com/mongo-express/mongo-express/blob/89ae24008e9405c5ef2e04d0457d54cae1c3a263/lib/routes/collection.js#L287

Please can you test with code of master branch?

**Comment by GerkinDev** [comment]
From the master branch, the projection is still not applied, and export endpoints still export complete objects
