### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by titan1230** [mongo-express/mongo-express#1595]
![image](https://github.com/user-attachments/assets/28fc6805-2482-48cd-9c14-8fbf1f90a41f)

Whenever I click on login, the page reloads and I stay on the same page
I cloned the master branch.

**Comment by xTudoS** [comment]
this page appears when you need to authenticate with mongodb server but either you  didn't provide this information or there is a mistake with them. 

If you didn't put them as ENV vars, try to put them and see if this page gets away.

**Comment by titan1230** [comment]
Yeh it was my mistake mongod service was not on.
