### ISSUE TITLE
What is the good documentation ? (Question)

### ISSUE THREAD

**Issue by Kilian-MERE-T2i** [mongo-express/mongo-express#1636]
Hi, i'm trying to configure mongo-express for some development, but i just found some inconsistencies between the [Github](https://github.com/mongo-express/mongo-express#usage-docker) documentation  and the [Docker Hub](https://hub.docker.com/_/mongo-express/) documentation.

Especially on the environments variables : 
- ME_CONFIG_MONGODB_ADMINUSERNAME
- ME_CONFIG_MONGODB_ADMINPASSWORD
and 
- ME_CONFIG_MONGODB_AUTH_USERNAME
- ME_CONFIG_MONGODB_AUTH_PASSWORD

Wich one should be used to define the mongo db password ? I've seen somewhere in 2020 that theses values have switched [StackOverflow post](https://stackoverflow.com/a/60342997), but we are in 2024 and the Github documentation about using docker image is still different than the DockerHub documentation.

Could you help me on that ?

These are not the only different variables between the documentation, there are more : 
| Present on Github documentation | Present on DockerHub documentation | Remark |
| -------------------------------------- | ------------------------------------------ | -------- |
| ME_CONFIG_MONGODB_AUTH_USERNAME | ME_CONFIG_MONGODB_ADMINUSERNAME | Are they the same ? |
| ME_CONFIG_MONGODB_AUTH_PASSWORD | ME_CONFIG_MONGODB_ADMINPASSWORD  | Are they the same ? |
| PORT | ME_CONFIG_MONGODB_PORT  | Are they the same ?  |
| ME_CONFIG_MONGODB_TLS_CA_FILE | | |
| ME_CONFIG_MONGODB_TLS_CERT_FILE | | |
| ME_CONFIG_MONGODB_TLS_CERT_KEY_FILE | | |
| ME_CONFIG_MONGODB_TLS_CERT_KEY_FILE_PASSWORD | | |

I will not make the full list but wich documentation is up to date ? Wich information is relevant ? 

Thanks in advance for you help.

**Comment by SleepyDeb** [comment]
Hello @Kilian-MERE-T2i, the updated version it's the one described in this repository README.md on this tag [v1.1.0-rc-2](https://github.com/mongo-express/mongo-express/tree/v1.1.0-rc-2)

To have a full comprehension of the available parameters you can read the config.default.js file, in there you will find all the parameter configuration bootstrap information you need.

**Comment by Kilian-MERE-T2i** [comment]
Thanks you, i will look into it :)
