### ISSUE TITLE
Using in a lambda function

### ISSUE THREAD

**Issue by nazariifenii** [mongo-express/mongo-express#1657]
Hey, I'm updating the package to use some of the features that are not working in the previous version, but the problem is that my app is running in lambda with serverless.

First, the old middleware import is not working(readme should probably be updated [here](https://github.com/mongo-express/mongo-express?tab=readme-ov-file#usage-express-4-middleware)), then I've patched the mongo-express/package.json to export ./lib/middleware instead of ./middleware and got the app running somehow by using the ENV variables, but when the app is rendered it's without any styles and I collections are not opened from the collections list.

I've read many issues but seems like no one is using a middleware function to run the service in lambda. 

Do you have any advice on how to update the library and be able to run in lambda? (I'm not very good at lambda and docker, so may simply just missing something)

**Comment by rtritto** [comment]
> ...when the app is rendered it's without any styles and I collections are not opened from the collections list

NPM version is outdated. Meanwhile, you can try to link `mongo-express` with master branch (`npm i mongo-express@github:mongo-express/mongo-express`) and, after the install, you should build (`cd node_modules/mongo-express` + `npm run build`).

**Comment by rtritto** [comment]
Try `npm i` before `npm run build`

**Comment by rtritto** [comment]
You should do `npm i` inside the `/node_modules/mongo-express`.

**Comment by rtritto** [comment]
The `mongo-express` version:
- on NPM is 1.0.2 (outdated)
- on master branch is 1.1.0-rc-1 (newest but not officially released to GitHub and to NPM)

**Comment by rtritto** [comment]
This error can be fixed with `npm run build`

**Comment by rtritto** [comment]
The `build-assets.json` is generated by build at root level (`/node_modules/mongo-express` folder).

**Comment by rtritto** [comment]
Can you try with:

```diff
+import path from 'node:path';
// ...

const middleware = async function (config) {
+  const __filename = fileURLToPath(import.meta.url);
+  const __dirname = path.dirname(__filename);
+  app.locals.assets = JSON.parse(fs.readFileSync(path.join(__dirname, './build-assets.json')));
// ...
```

**Comment by rtritto** [comment]
Thanks, I created #1660 with improved code (if you want, you can test/review)

**Comment by rtritto** [comment]
> It looks like a permission issue. I saw there is csrfToken used, do I need to include it in my express app? Or maybe something different?

Did you set `ME_CONFIG_SITE_COOKIESECRET` and `ME_CONFIG_SITE_SESSIONSECRET` env vars?

**Comment by rtritto** [comment]
Version [1.1.0-rc-2](https://github.com/mongo-express/mongo-express/releases/tag/v1.1.0-rc-2) was released.

For other issues, please open a new issue.

**Comment by NeverBehave** [comment]
To follow up: why `build-assets.json` needs to be manually built when used as a module (express middleware)? Is this intentional? 

For the part published in npm, the `build-assets.json` seems required to run/integrate this package into other projects. If so, should this file be included in the final artifacts, or at least done in [install script](https://docs.npmjs.com/cli/v9/using-npm/scripts#examples)?
