### ISSUE TITLE
Official Docker image on Docker Hub

### ISSUE THREAD

**Issue by pataquets** [mongo-express/mongo-express#181]
Would be great to have an official Docker image on Docker Hub, since there are lots of them and finding one built from this very same repo Dockerfile would be more trustable and would help focusing contributors Dockefile enhancements.
Thus, documentation could easily include a canonical "docker run" statement to quickly spin up a ME instance with just a single command.
There are also "automated builds" available that can be triggered on each commit automatically:
https://docs.docker.com/docker-hub/builds/

**Comment by wulfsolter** [comment]
I personally don't use Docker Hub, but maybe @knickers has some insight to the feasibility of this request?

**Comment by knickers** [comment]
I would be willing to look into building a Docker official image. Until then @pataquets, you can use [knickers/mongo-express](https://hub.docker.com/r/knickers/mongo-express/) as an easy "docker run" to quickly spin up an instance. I build it straight from the latest npm version as often as I can (which is usually within a day or two of the latest version).

**Comment by wulfsolter** [comment]
Manual builds? Ouch. I'll look into getting Travis set up to automagically build Docker? I don't use it myself much so not to sure, but I'll have a wee look https://docs.travis-ci.com/user/docker/

**Comment by tianon** [comment]
@wulfsolter I think what @knickers meant by manual is bumping the version number that's embedded in the `Dockerfile` when there's a new release -- the build itself is managed by [Docker's Automated Builds](https://docs.docker.com/docker-hub/builds/), so should always be up to date :+1:

**Comment by wulfsolter** [comment]
I was going to write a quick wee pre-commit test to make sure I don't update `package.json` version without updating `Dockerfile`, but I can't see a version string in the [Dockerfile](https://github.com/andzdroid/mongo-express/blob/master/Dockerfile)

**Comment by knickers** [comment]
Oh sorry, @tianon is talking about a separate repo with my own `Dockerfile`
here https://github.com/knickers/mongo-express. This one pulls a specific
version from npm.

The `Dockerfile` in https://github
com/andzdroid/mongo-express doesn't need a version number because it builds
from the source code already in the directory.

**Comment by wulfsolter** [comment]
Gotcha. Big fan of automating manual tasks and avoiding double handling. Let me know if there's anything I can do to help - Travis is hooked in https://travis-ci.org/andzdroid/mongo-express so if there's some way to get Travis to update version numbers that might save the hassle.

**Comment by knickers** [comment]
@wulfsolter, I created a new github organization for mongo-express and invited you as an owner. What do you think about moving development there?

**Comment by wulfsolter** [comment]
Good call! @knickers

**Comment by knickers** [comment]
Hey @wulfsolter. The docker developers are taking forever getting around to reviewing the pull request for our official mongo-express image. I think we should include a link to my [knickers/mongo-express](https://hub.docker.com/r/knickers/mongo-express/) image in the `README.md` so people will know that it is officially supported. What do you think?

**Comment by wulfsolter** [comment]
Good plan :+1:

**Comment by knickers** [comment]
Awesome, done :smile:

**Comment by knickers** [comment]
The official docker image was approved today! :birthday: It is now available here: https://hub.docker.com/_/mongo-express/

**Comment by pataquets** [comment]
Finally gave a try to the new official image. It works beautifully.
Thank you very much everyone!
