### ISSUE TITLE
mongo-express logo

### ISSUE THREAD

**Issue by knickers** [mongo-express/mongo-express#186]
Does someone have a high-res or svg version of the logo that we can add to the repository?

**Comment by wulfsolter** [comment]
Origin unknown, so redrew in AI. https://github.com/mongo-express/mongo-express/commit/20295d2b41e733f5751fc11ed925e4caabb919c6

Leaf is more asymmetrical, but it's an exact vector from MongoDB.

**Comment by knickers** [comment]
Oh, thanks @wulfsolter!
