### ISSUE TITLE
Reopening #166

### ISSUE THREAD

**Issue by lcrocker** [mongo-express/mongo-express#189]
I couldn't figure out how to re-open a close issue here, which I'd like to do with #166 (Use of const in strict mode).

I get this error running with Node 0.10.37, mongo-express 0.30.22. Using "nodejs --harmony" gets past that, but chokes on line 16 of app.js: updateNotifier({ pkg });

I can workaround by downgrading, but it would be nice to use the latest without having to change Node versions once a week.

**Comment by wulfsolter** [comment]
`app.js` is calling [update-notifier](https://www.npmjs.com/package/update-notifier#simple-example) as recommended, so I think it might be that Node 0.10.37 is simply too old to support that syntax.

Node 0.10.37 is very old and has a few known and pretty major security vulnerabilities, while there are many great performance enhancements, bug fixes, improved ES2015 / ES2016 support with newer versions of V8 and much much more in the newer versions of NodeJS.
