### ISSUE TITLE
broken

### ISSUE THREAD

**Issue by streamnsight** [mongo-express/mongo-express#190]
Not sure what the changes have been here, but I guess I was using the version from 2 releases ago and the last 2 are broken:

First, the config had to be changed to account for the host, or it defaults to localhost which is not accessible outside in a Docker container.

Second, whenever I try to view a document, I get a blank page (with v0.29.10) or a 'document does not exists' with the previous version, while it is perfectly able to list documents. 
What's going on? 
My _id's are not Mongo Ids, they're bigInt as String. BIgInt are always a bit of a trouble with JS, but as a String that should not be, unless you guys are trying to parse as a number.

**Comment by wulfsolter** [comment]
Can you update to latest? There's been quite a bit of work on refactoring _ids recently.

**Comment by streamnsight** [comment]
as i mentionned, the last 2 versions i tried are broken for me.

**Comment by streamnsight** [comment]
unless you mean update to master

**Comment by wulfsolter** [comment]
Update to latest npm version (0.30.23) please. 

I've had a big play with _ids as strings, ints, bigInts and just can't figure it out. 

As for Docker, have you seen https://github.com/mongo-express/mongo-express-docker ?

**Comment by wulfsolter** [comment]
Any luck @streamnsight ?
