### ISSUE TITLE
Incorrectly export DBRef field

### ISSUE THREAD

**Issue by zxkane** [mongo-express/mongo-express#191]
I have a collection with record,

```json
{
    "_id": ObjectID("56cffed8661262050036471c"),
    "abc": DBRef("c2", "sss22222222")
}
```

mongo-express exports it as below,

```
{"_id":{ "$oid": "56cffed8661262050036471c" },"abc":DBRef("c2", "sss22222222" }}
```

which can not be imported by `mongoimport`

```shell
mongoimport -d test -c col c.json             
2016-02-26T15:36:56.721+0800	connected to: localhost
2016-02-26T15:36:56.722+0800	Failed: error processing document #1: invalid character '}' after constructor argument
2016-02-26T15:36:56.722+0800	imported 0 documents
```

**Comment by wulfsolter** [comment]
I've not needed DBRef()s so can't reliably test...

Could you try adding
 `sJson = sJson.replace(/DBRef\(/g, '{ "$ref": ');`
to https://github.com/mongo-express/mongo-express/blob/master/lib/bson.js#L106-L112 which will fix the invalid syntax.

But $ref [should only be a single value](https://docs.mongodb.org/manual/reference/database-references/#dbref-explanation) so I'm not sure your record is valid.

**Comment by wulfsolter** [comment]
https://github.com/mongo-express/mongo-express/commit/80101374076082f952da64d132f78fd3650c1295
