### ISSUE TITLE
Cannot access mongo-express from a remote PC

### ISSUE THREAD

**Issue by aakashsy** [mongo-express/mongo-express#193]
I was unable to forward mongo-express port for remote access. Cannot even access it on my local network. Works only on localhost

**Comment by wulfsolter** [comment]
[Line 83 in the default config](https://github.com/mongo-express/mongo-express/blob/master/config.default.js#L83) sets what host to listen for.

Set this to the IP address of where you wish to take requests from, or 0.0.0.0 ([wikipedia article on 0.0.0.0](https://en.wikipedia.org/wiki/0.0.0.0)) to allow requests from any IPv4 address

**Comment by wulfsolter** [comment]
It even says this at startup:
<img width="576" alt="screen shot 2016-02-27 at 11 34 00 pm" src="https://cloud.githubusercontent.com/assets/1692132/13372509/a612f096-ddaa-11e5-80ce-29cccfe112b2.png">
