### ISSUE TITLE
mongoose ref not supported?

### ISSUE THREAD

**Issue by Muffasa** [mongo-express/mongo-express#197]
I have a production server that uses mongoose.
on the modules schemas the relations defined like this:
`event:{type:mongoose.Schema.Types.ObjectId,ref: 'Event',required:true}`

on the db property saved like this:
` "event": ObjectID("56d0594d29e2110d00b44c89")`

In order to have the ability to link docs with mongo-express must I update my server to add DBRef() properties to all of my models? 

I cant understand why mongo express dosent treat ObjectId() as refs.

Isnt there any way to link docs in mongo-express only by id?

**Comment by wulfsolter** [comment]
Could you upload (gist/pastebin) a replication case? I'm not sure how to replicate

**Comment by wulfsolter** [comment]
@Muffasa ?

**Comment by Muffasa** [comment]
Im sorry for my late response, can you explain me what exactly you want me to upload?

**Comment by wulfsolter** [comment]
Export of a minimal DB to replicate the issue? With documents that are working as intended, and ones that are failing. That way I can import the DB, have a look around and see what I can do to fix the issue.

**Comment by Muffasa** [comment]
there is no issue my friend. i was wondering why the DBRef() property must be a part of the doc and why cant it work the exact same way with ObjectId().

isnt there a script that adds DBRef() to all the docs based on the ObjectId()?

**Comment by wulfsolter** [comment]
:) I really don't know, sorry. I've not encountered a similar situation before nor come across a script that adds DBRef()s
