### ISSUE TITLE
How can I made an advanced query?

### ISSUE THREAD

**Issue by alatriste-lee** [mongo-express/mongo-express#200]
What should I filled in "Query" and "Fields" blanks in "Advanced" mode?

Here is what I filled in "Query" blank : "db.collection.find().sort({_id:-1}).limit(1) ", and then I don't konw what to fill in "Fields" blank.  After I hit "Find",here is what I got : "Query entered is not valid". 

Thanks a lot.

**Comment by wulfsolter** [comment]
Added usage to `README.md`, updated the form's field names and pushed to npm, HTH.

https://github.com/mongo-express/mongo-express/blob/master/README.md#search

**Comment by alatriste-lee** [comment]
Thankyou very much, your hint is truely help.

This can work now: 
"Query" blank filled in : {"some fild etc.": { $gt:  "2015/12/19 0:00:00", $lt:  "2015/12/19 0:00:02" }   } 
"Filds" blank filled in: nothing, then click "Find".

However, The mongo server returned 3 pages output, but only the 1st page can read, when click "Next" or page number,  mongo-express shows: "No documents found. ". I think there is something I didn't make right or there's a bug.
