### ISSUE TITLE
 SyntaxError: Use of const in strict mode - Mongo Express

### ISSUE THREAD

**Issue by AlexL777** [mongo-express/mongo-express#201]
Hello Developers,
I need your support and although I have Mongo Express installed on CentOs 7 and when I run this command, I get the above error message appears.

mongo-express -u xxxxxxxxx -p xxxxxxxx -d xxxxxxx

    SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3

How can it be, and how can you fix it?

Thanks in advance.

**Comment by wulfsolter** [comment]
Please upgrade your version of NodeJS or use the `--harmony` flag. See this [StackOverflow question](https://stackoverflow.com/questions/22603078/syntaxerror-use-of-const-in-strict-mode) for more details. 

Old versions (such as 0.10.x) have a number of vulnerabilities and are approaching end of life very soon.
![NodeJS Release Schedule](https://raw.githubusercontent.com/nodejs/LTS/master/schedule.png)
