### ISSUE TITLE
absolute path problems

### ISSUE THREAD

**Issue by Morriz** [mongo-express/mongo-express#203]
I believe it would be possible with a quick fix to remove all absolute paths in the application, no?

The current setup is not kubernetes proxy friendly, and breaks when not run in it's own domain...unneeded imo

**Comment by wulfsolter** [comment]
Sure. PR?

**Comment by Morriz** [comment]
Just sent :)

**Comment by wulfsolter** [comment]
Merged and updated on npm. Thanks!

**Comment by Morriz** [comment]
Tested by clicking around tho, hope it's alright ;)
