### ISSUE TITLE
support authenticationDatabase

### ISSUE THREAD

**Issue by dongliu** [mongo-express/mongo-express#206]
The current config.js and command line options assume that the user and admin to auth is in the same database as the database to connect. 

This assumption is not true when using the admin db to define users for access control. That is
 --authenticationDatabase admin 
in mongo command line or in mongoose 
 "auth": {
    "authdb": "admin"
  }

**Comment by zeusro** [comment]
+1

**Comment by wulfsolter** [comment]
PR?

**Comment by grtfou** [comment]
Does mongo-express support mongodb 2.6.x?
I can't pass the authentication and got error message
`MongoError: not authorized on admin to execute command { serverStatus: 1 }`

However, it's work on Robomongo when **Auth mechanism** set **MONGODB-CR**.
Have any solutions on mongo-express?

Thanks,

**Comment by wulfsolter** [comment]
Yes, ME supports 2.6.x.

The default pages show status information (such as number of rows). The
error message suggest you do not have those permissions.

**Comment by dozoisch** [comment]
This issue has gone stale. Please open a new issue if that is still a problem.

**Comment by natvaldev** [comment]
does it support authenticationDatabase?
