### ISSUE TITLE
HTML code are not escaped when the property is too long..

### ISSUE THREAD

**Issue by zhchbin** [mongo-express/mongo-express#209]
Steps to reproduce
```bash
# db name is test
> db.foo.insert({"test": "<img onerror='alert(1)' src='1'/><message></message>"})
```
Path: /db/test/foo
![1](https://cloud.githubusercontent.com/assets/1787294/14036007/b679f22a-f26f-11e5-9cd2-4497ccac3a85.PNG)

Version: mongo-express@0.30.38, install via: `npm install mongo-express`

**Comment by wulfsolter** [comment]
Thanks very much for great reproduction steps @zhchbin :)
