### ISSUE TITLE
Project is missing an Open Source License. 

### ISSUE THREAD

**Issue by ShahBinoy** [mongo-express/mongo-express#213]
Please provide the OS licence that this project is following.

**Comment by wulfsolter** [comment]
Is https://github.com/mongo-express/mongo-express#license insufficient?

**Comment by ShahBinoy** [comment]
Sorry, dunno how I missed that, thanks

**Comment by AlekSi** [comment]
Various automated license checking tools can't handle license in the README file. For example, GitHub itself does not show the license information:

<img width="183" alt="CleanShot 2022-11-15 at 20 32 42@2x" src="https://user-images.githubusercontent.com/11512/201974636-006018e6-d2ce-4e4a-8b79-561e92996729.png">

They recommend to put it into a separate file: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#determining-the-location-of-your-license

**Comment by rtritto** [comment]
FYI @shakaran @BlackthornYugen

**Comment by shakaran** [comment]
@AlekSi Fixed in https://github.com/mongo-express/mongo-express/pull/1044

**Comment by AlekSi** [comment]
Thank you!
