### ISSUE TITLE
Issue with docker

### ISSUE THREAD

**Issue by psychok7** [mongo-express/mongo-express#215]
When i run `docker run -it --rm -p 8081:8081 --link mongo_1:mongo mongo-express` i now get a `docker: Error response from daemon: Cannot link to /mongo_1, as it does not belong to the default network.`

This command used to work before i upgraded to the latest docker `1.11.0` and docker-compose `1.7.0`

How can i fix it?

**Comment by knickers** [comment]
First try using the new official image:

docker run -it --rm -p 8081:8081 --link mongo_1:mongo mongo-express.

But I'll look into this later today.

**Comment by psychok7** [comment]
@knickers i tried both images with no luck

**Comment by knickers** [comment]
Hm. @psychok7, it seems that this could be a `docker-compose` issue. [Here is the same error](http://stackoverflow.com/questions/36489696/cannot-link-to-a-running-container-started-by-docker-compose). He fixed it by running

```
$ docker network ls
```

and finding the network that `docker-compose` created. Then he added the network with `--net` to the run command.

```
$ docker run -it --rm -p 8081:8081 --link mongo_1:mongo --net my_app_default mongo-express
```

My `docker-compose` doesn't create a new network, so I can't test this though.

**Comment by psychok7** [comment]
@knickers it only works if i use the "old image" like `docker run -it --rm -p 8081:8081 --link mongo_1:mongo --net my_app_default knickers/mongo-express` with the new `mongo-express` image it only steps into the container but the server does not run.

Thanks anyways

**Comment by tmundt** [comment]
Many thanks to @knickers 👍 I had that problem and solved it with your solution!
I created a wordpress and mysql database with docker-compose. Then I tried to docker run a phymyadmin image, what failed. After identifying the created network and applying its name while docker running the new image, everything worked perfect. :-)

**Comment by knickers** [comment]
Awesome, I'm going to mark this issue as closed then :panda_face:.
