### ISSUE TITLE
"ObjectIDs must be 24 characters long!"

### ISSUE THREAD

**Issue by hkors** [mongo-express/mongo-express#218]
Hello,

When I try to find documents with an ObjectID, I receive the message "ObjectIDs must be 24 characters long!". I've been counting the characters of my ObjectIDs, and they are 24 characters. Is this a bug?

![mongo express](https://cloud.githubusercontent.com/assets/17003285/14816940/11900a84-0bb4-11e6-8939-a89e1feba57a.png)

I'm using version 0.30.52 of mongo-express and version 3.0.7 of MongoDB.

**Comment by zeusro** [comment]
+1
@hkors 
but you can change the type from objectid to string(columnname is need) and it will "solve" this issue

**Comment by wulfsolter** [comment]
PRs are far more welcome than +1s @zeusro
