### ISSUE TITLE
Simple Search - Not Working

### ISSUE THREAD

**Issue by laurin1** [mongo-express/mongo-express#221]
Am I supposed to have to enter key AND value? If do, I get no results, if I don't, I get all documents. I've tried various combinations and search types (string, regex), but nothing seems work.

**Comment by wulfsolter** [comment]
Key is the column name, value is the value present in the column.

For example:

No search (all documents)
<img width="1233" alt="screen shot 2016-04-30 at 3 03 59 am" src="https://cloud.githubusercontent.com/assets/1692132/14920138/3e93d1ea-0e80-11e6-860c-0a0a5aa22a01.png">

Key is "foo" value is "bar"
<img width="1236" alt="screen shot 2016-04-30 at 3 04 09 am" src="https://cloud.githubusercontent.com/assets/1692132/14920139/3e93c100-0e80-11e6-9097-8f993838b67b.png">

**Comment by laurin1** [comment]
Doh! I got confused, but we store all of our documents with a property named "Key". :)
