### ISSUE TITLE
Feature request: Create a view of a collection for managers or editor

### ISSUE THREAD

**Issue by gianpaj** [mongo-express/mongo-express#224]
Similar to what https://www.humongous.io/ provide.

Would be great if a Database Administrator could easily create View of the data in a collection so a Manager or the same Administrator could edit some simple table.

For example accessing a collection of blog posts, and being able to change the fields without having access to the entire database.

**Comment by wulfsolter** [comment]
Something like https://docs.mongodb.com/manual/core/collection-level-access-control/ ?

**Comment by gianpaj** [comment]
More like traditional Relational views

**Comment by dozoisch** [comment]
This feature is quite big. I personally don't have the time to do something like that and we haven't seen much demand for it. We're open to PRs. I'll close this issue for the time being
