### ISSUE TITLE
display issue when &query= is the the url with deep documents

### ISSUE THREAD

**Issue by LewisMcMahon** [mongo-express/mongo-express#225]
When the url is [host]:8081/db/MPC/item the collection looks like [this](http://i.imgur.com/x2VXrtj.png) which is how it should look.

But if `query=` is in the url even when empty as it is when you click next all the json documents are not collapsed as seen [here](https://i.imgur.com/xlP2AjQ.png?1) i believe this is caused by a JavaScript error `Uncaught ReferenceError: getParameterByname is not defined`

If you remove `query=` from the url so you end up with something like `?skip=0&key=&value=&type=&query=&projection=` the issue no longer occurs.

**Comment by wulfsolter** [comment]
Yep, good spotting @LewisMcMahon 

Seems an uppercase 'N' got dropped in https://github.com/mongo-express/mongo-express/commit/e7dc3a6bd3e50af283116483d40b74b761a73f17#diff-719c36e360c37fccfb9f4ed48a2bace6R14

New version available on npm.
