### ISSUE TITLE
Cannot query on ObjectID

### ISSUE THREAD

**Issue by rubenvereecken** [mongo-express/mongo-express#229]
I tried querying using `ObjectID("...")` as value and picking ObjectID as value type. No results found, and after querying the value box changes as can be seen in this screenshot:

http://screencloud.net/v/sRNV

Tried different ways of querying on ID but to no avail. Any ideas?

**Comment by rubenvereecken** [comment]
Of course the "not found" was my own fault :). Still the incorrect depiction of `[object Object]` can be fixed with a proper `toString` on ObjectIDs I think?

**Comment by rubenvereecken** [comment]
This same bug also messes up paging because the object query will be borked after the first page; subsequent page queries will fail.

**Comment by crobinson42** [comment]
WTF.. lol, how do you do a simple search of an ObjectID field?

I get this error:

> ObjectIDs must be 24 characters long!

**Comment by crobinson42** [comment]
It doesn't make sense to have to wrap the value with 
`ObjectID()` when the drop down selects ObjectId.. weird UX.

**Comment by heartnetkung** [comment]
@rubenvereecken 
I think my pull request already fix the paging issue. 
https://github.com/mongo-express/mongo-express/pull/273

@crobinson42 
Another pull request of mine also fix yours :)
https://github.com/mongo-express/mongo-express/pull/277

**Comment by dozoisch** [comment]
Seems like all issues are fixed,  I'll cose this issue for now. Feel free to ping me if there is something left.
