### ISSUE TITLE
Missing Databases

### ISSUE THREAD

**Issue by LeandroFavero** [mongo-express/mongo-express#231]
Hi,

I just updated, using Node v4.4.3 and 6.0.0, with MongoDB 3.2.6, but not show any Database. Just "db".

I tried create a new database but received the message: Could not create collection.

I was logged like Admin.

In version "0.30.54" works, but in the lastest version "0.30.57" this issue appears.

What can be?

**Comment by wulfsolter** [comment]
Can you try reverting https://github.com/mongo-express/mongo-express/commit/4124f18f166af51d345504dc5c064366099a2211

Possibly just easiest to remove the line in lib/router.js by hand.

**Comment by heardy** [comment]
@wulfsolter I had the same issue and I removed the line you suggested and it now works. Thanks

Is there a fix for this in a release?

**Comment by younanjo** [comment]
same issue here!

**Comment by r3wt** [comment]
same here :-1: for bad commits

**Comment by wulfsolter** [comment]
I'm quite busy with my actual paying job and not seeing any PR's from you guys.....

 👎 for unhelpful emoticons without PRs. Said commit solved other issues, you're clearly in no state to make a call on whether they were good or bad, nor have you offered any help or a PR to address the issue. A bit of a dick move really @r3wt .

**Comment by r3wt** [comment]
@wulfsolter Nevermind the fact that this change broke our app (thus affecting my paying job as well), in interest of this project and its usefulness i'll play ball. point me to the issue that this was fixing, and i will attempt to find a fix for both.

**Comment by wulfsolter** [comment]
Would be much appreciated @r3wt :) As [very first comment in this thread](https://github.com/mongo-express/mongo-express/issues/231#issuecomment-220494907) I outlined the [commit](https://github.com/mongo-express/mongo-express/commit/4124f18f166af51d345504dc5c064366099a2211), which in turn contains the issue number https://github.com/mongo-express/mongo-express/issues/228 .

Probably time for a bit of a refactor, but as I can replicate neither locally, I'm only guessing in the dark.

**Comment by LeandroFavero** [comment]
hi,

I updated to Node 7, get the latest mongo-express version and change to admin: true.

And this works!

Very nice!!!!

**Comment by dozoisch** [comment]
Is that still a thing? Feel free to comment if it is. But without more information and other reports, I'll just close this. Ping me if it is and I will reopen.
