### ISSUE TITLE
Export in CSV

### ISSUE THREAD

**Issue by IonicaBizau** [mongo-express/mongo-express#237]
Exporting in JSON is cool, but it would be really nice to have an export as CSV thingy that will create a CSV file.

**Comment by dozoisch** [comment]
We're always open to PRs!

**Comment by wulfsolter** [comment]
I'm using https://github.com/knrz/CSV.js/ in a few projects, very nice to use.

Something like:

    exportCSV(req, res) {
      const csv       = require('fast-csv');
      res.setHeader('Content-Type', 'application/download');
      res.attachment('Filename.csv');
      this.getData({
        //
      },
      (error, result) => {
        if (error) {
            //
          return res.send(error, 200);
        }
        csv.write(result.data, { headers: result.headers, discardUnmappedColumns: true }).pipe(res);
      });
    },

**Comment by IonicaBizau** [comment]
Thanks, @dozoisch! ✨
