### ISSUE TITLE
BlueMix env structure changed

### ISSUE THREAD

**Issue by agov** [mongo-express/mongo-express#240]
BlueMix env structure changed:
`var dbLabel = 'mongodb-2.4';`
In sample config no longer works, it should be:
`var dbLabel = 'mongodb';`

This change is not yet visible on Environment Variables tab.

**Comment by youleaf** [comment]
up. It took me 5 days to figure this out.
I'm done with bluemix: no documentation, no support, no communication with customers. I've opened a support ticket 5 days ago and received no answer. Go AWS, guys.

**Comment by lainor** [comment]
Is the variable name changed again to  'mongodb-2.4'?

**Comment by ShvedPeter** [comment]
how i can change that in config file? npm modules reinstall every time when i restart app. how i can edit config file?

**Comment by dozoisch** [comment]
@ShvedPeter The easiest way right now if you don't want to use the express middleware, it's to have your own config.js file and copy it as a post install step. This lines imports a config.js file https://github.com/mongo-express/mongo-express/blob/master/app.js#L29

**Comment by dozoisch** [comment]
I don't use bluemix at all, so I'd be open for a PR fixing this, since I can't test it.

**Comment by dozoisch** [comment]
Since no one answered. I'll close this issue. Feel free to open a new issue/pr to fix it.
