### ISSUE TITLE
Doesn't support router-level middleware

### ISSUE THREAD

**Issue by smithy545** [mongo-express/mongo-express#244]
I tried to use lib/middleware.js by using it on a router instead of on the base app but it would redirect to the wrong location. I had to use lib/router and copy all the template files my views directory to get it to work.

For example I would set it up like this:
app.js

```
app.use('/admin' , require('./routes/admin'));
```

admin.js

```
var mongo_express = require('mongo-express/lib/router');
var mongo_express_config = require('../config/admin.js');

var admin = express.Router();
admin.use('/', mongo_express(mongo_express_config));

module.exports = admin;
```

And when I clicked links on the page instead of redirecting to 'www.mywebsite.com/admin/db/dbname' it would redirect to 'www.mywebsite.com/db/dbname'. I tried changing the base url but that did nothing. I'm using the router.js file directly now but my default template language is different so it's kind of a pain. If there's a fix I'm not seeing please let me know.

**Comment by dozoisch** [comment]
That should be supported now with #320.
