### ISSUE TITLE
Error: Invalid filter "stringDocIDs" 

### ISSUE THREAD

**Issue by aceofspades** [mongo-express/mongo-express#247]
`Error: Invalid filter "stringDocIDs" on line 269 in file .../node_modules/mongo-express/lib/views/collection.html`

Any idea what this means?

**Comment by muxahuk** [comment]
it means that html engine ( swig ) cannot find filter `stringDocIDs`

try these solution: https://github.com/mongo-express/mongo-express/issues/60#issuecomment-124654469

**Comment by aceofspades** [comment]
Rewording the error message hasn't helped--Google returns nothing for `stringDocIDs` and I have no idea what that is, what it does, whether it has something to do with swig or mongo or the combination, etc...

That link wasn't much help, unfortunately. Shouldn't this work right out of the box? Or should I have to learn and research a templating engine and understand how filter extensions work, etc?

**Comment by muxahuk** [comment]
Well, u'v asked what it means - i'v answered..
found similar problem in issues and posted u a link..

I presonally don't have these error. But yes, it should work from the box.

I don't know what couses these problem to you.. Try reinstalling, try updating node modules atc..
To help u we need at least more info than `Error: Invalid filter...`

PS: you could use "find in these repo" to find these function, witch isn't working for you..
