### ISSUE TITLE
Incorrectly defined mountpath when mongo-express used as middleware

### ISSUE THREAD

**Issue by amberv0** [mongo-express/mongo-express#256]
Here is my setup: 
```
var mongo_express = require('mongo-express/lib/middleware');
var mongo_express_config = require('mongo-express/config.default')

app.use('/mongo_express', mongo_express(mongo_express_config))
```

in `config.default` (for simplicity) I set
```
baseUrl: process.env.ME_CONFIG_SITE_BASEURL || '/mongo_express/'
```
When I open the url in my browser, static assets are not loaded correctly: they are not prefixed with `/mongo_express/`, and so not found. That is, here is the path with which I can access an image - `http://localhost:1337/mongo_express/images/mongo-express-logo.png`, but what the page requests is `http://localhost:1337/images/mongo-express-logo.png`, which is not found. 
Here is the part of the code of the main page:
  ```
<base href="/">
  <meta charset="utf-8">
  <title>Home - Mongo Express</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <link href="/stylesheets/bootstrap.min.css" rel="stylesheet">
  <link href="/stylesheets/bootstrap-theme.min.css" rel="stylesheet">
  <link href="/stylesheets/style.css" rel="stylesheet" />
```

We see that the paths are not prefixed. 
When I mount the app separately with `node app --port 3000` everything works just fine.

I traced the origins of the problem back to the line 
`res.locals.baseHref       = req.app.mountpath + (req.app.mountpath[req.app.mountpath.length - 1] === '/' ? '' : '/');` in `lib/router.js`
where the `req.app.mountpath` is equal to '/' instead of correct mountpath ('/mongo_express/'). So it should be easy to fix.

Thanks!

**Comment by wulfsolter** [comment]
Hi @amberv0 - My company has moved off MongoDB, so I'm rarely here these days.

I think you're on the right path with `lib/router.js` and `req.app.mountpath` though so if you put together a PR I'll happily merge :)

**Comment by levigroker** [comment]
I too have this exact issue. @amberv0 Have you come up with a workaround?

**Comment by amberv0** [comment]
@levigroker , I'm investigating the origins of the issue (why `req.app.mountpath` is not correct). But if you need a quick fix for now, you can just modify `lib/router.js` to replace
`res.locals.baseHref = req.app.mountpath + (req.app.mountpath[req.app.mountpath.length - 1] === '/' ? '' : '/'); in lib/router.js`
with 
`res.locals.baseHref = config.site.baseUrl;`
It fixes the problem and in both modes everything works correctly, but I don't feel like being ready to submit a PR since I don't see the "whole picture" of the issue.

**Comment by amberv0** [comment]
Ok, I think I found the origins of the issue. Here it is: difference in versions of Express. 
Basically, my version of Express is 3.21.2, and mongo-express currently uses 4.13.4. In 4.0.0 the change was made:
`app.route` -> `app.mountpath` when mounting an express app in another express app
So I suppose that the version 4 can't correctly detect the `mountpath` when being mounted from the version 3. 
@levigroker , could you confirm that it's also your case, that you are using Express 3.x.x ?

**Comment by levigroker** [comment]
Thanks @amberv0 Unfortunately, no... we have Express as a dependency with the version indicated as `^4.14.0`.

**Comment by trivender** [comment]
I am also facing similar issue :(

**Comment by levigroker** [comment]
@trivender I have a pull request in with a fix... #259 (open, still, unfortunately)

**Comment by amberv0** [comment]
@wulfsolter, could you merge that please?

**Comment by trivender** [comment]
@levigroker I tried your fix:


with ``baseUrl: process.env.ME_CONFIG_SITE_BASEURL || '/'`` able to access mongo-express but without stylesheets but changing to `baseUrl: process.env.ME_CONFIG_SITE_BASEURL || '/mongo_express/'` causes another error #257 

I am new to nodejs and its been whole day I am struggling to fix it.

**Comment by levigroker** [comment]
@trivender Sorry, I'm not familiar with the `ME_CONFIG_SITE_BASEURL` environment variable or what it's supposed to do... all I can tell you is that we had to configure mongo-express with the main router, as it would not work if it was in a nested router.

So, we have our `app.js` setup like this:

```
const mongoExpress = require('mongo-express/lib/middleware');
let mongoConf = require('mongo-express/config.default.js');

const app = express();               
app.use('/mongo', mongoExpress(mongoConf));
```
