### ISSUE TITLE
Will it support managing indexes?

### ISSUE THREAD

**Issue by KJlmfe** [mongo-express/mongo-express#258]
It would be better if it has an interactive way to manage indexes :)

**Comment by wulfsolter** [comment]
PRs are welcome :)

**Comment by dozoisch** [comment]
@heartnetkung I guess one of the first step if you want to do it could be to add a "re-index" button under a collection (in the tools section). I'd say it's a common operation that could be useful to do. 

Other than that for the index management, we could just list the indexes with a delete button, so they can be removed. 

like 

```
| name    | colums                | bg   | actions    |
| ------- | ----------------------| -----| ---------- |
| index_1 | - col1 -col2 (as lis) | true | (trashcan) |
```

and we can add other actions after ward.

**Comment by heartnetkung** [comment]
@dozoisch 
Sounds good. Though I've never use re-index in my life haha. 

By the way, what's bg - true? Also, what about sparse and unique?

**Comment by heartnetkung** [comment]
How about something like this? (ignore reindex button. they'll be relocated to tools section)

![screenshot from 2016-10-28 16 22 51](https://cloud.githubusercontent.com/assets/1158685/19801981/a4436b06-9d2b-11e6-9fe5-00159886c259.png)

**Comment by dozoisch** [comment]
I don't know if ReIndex can be done per index, I know there is a db.collection.reIndex() https://docs.mongodb.com/manual/reference/command/reIndex/ which is global to the collection.

Bg was for background! That could go in the attributes column I guess! 
Design Looks good to me !

**Comment by dozoisch** [comment]
I think we can close it for now. As of 0.32, it's now possible to delete an index or re-index a collection. The only thing not supported is index creation, which still needs to happen manually.
