### ISSUE TITLE
Does not run :(

### ISSUE THREAD

**Issue by alvarodecastro74** [mongo-express/mongo-express#260]
We've installed globally it on a Centos 6.5 machine running MongoDB shell version: 2.6.12

When we type "mongo-express" we get
_/usr/lib/node_modules/mongo-express/app.js:5
const clc             = require('cli-color');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:945:3_

**Comment by wulfsolter** [comment]
People not reading the first line of usage :( https://github.com/mongo-express/mongo-express#usage-npm--cli 

Requires node 4.0.0 or higher as stated in the usage. And if you're not on 4.x.x or higher by now, you're about to have all support dropped in the next few weeks and shouldn't be trusted to play with new toys. https://github.com/nodejs/LTS

Update your node.
