### ISSUE TITLE
Searching in nested json

### ISSUE THREAD

**Issue by cahernanz** [mongo-express/mongo-express#261]
Is it possible to make simple searches in nested JSON documents, i mean, for example fields name, age, brand or model?. In main table will appear just person and car.

Example, grand prix inscription

{
 person:
            {
              name: ray,
              age: 21
             },
 car: {brand:bmw, model: 3 series}
}

**Comment by wulfsolter** [comment]
https://docs.mongodb.com/manual/tutorial/query-documents/#query-on-embedded-documents
