### ISSUE TITLE
No documentaion for replicaSet with SSL certificate

### ISSUE THREAD

**Issue by vijayaa** [mongo-express/mongo-express#269]
We need to connect mongodb with ssl using certicate  with replicaSet . Please provide documentation or example configuration

**Comment by dozoisch** [comment]
For SSL there are parameters that are documented. See https://github.com/mongo-express/mongo-express/blob/da8d5cc034fb9c1f6347fdd5a89a71c901510474/config.default.js.

For replicaSet you can connect by passing an array in the server field. See https://github.com/mongo-express/mongo-express/pull/105

**Comment by dozoisch** [comment]
PRs are welcome if you want to create a complete example.
