### ISSUE TITLE
Openshift - The cartridge manifest must be smaller than 20480 bytes.

### ISSUE THREAD

**Issue by kauegimenes** [mongo-express/mongo-express#286]
The cartridge manifest at 'https://github.com/mongo-express/mongo-express.git' could not be downloaded: The cartridge manifest at 'https://github.com/mongo-express/mongo-express.git' must be smaller than 20480 bytes.

**Comment by dozoisch** [comment]
@kauegimenes I have no idea how cartridge manifest works on Openshift, but I don't think we support that platform how of the box. Instead you should use the middleware provided https://github.com/mongo-express/mongo-express#usage-express-4-middleware
