### ISSUE TITLE
Index Creation

### ISSUE THREAD

**Issue by dozoisch** [mongo-express/mongo-express#287]
0.32 added index deletion & collection re-indexing. 

We're missing index creation. We're open to PRs if someone want's to take care of this.

**Comment by smartmasks** [comment]
I have knowledge in this section how can i help you @dozoisch

**Comment by heartnetkung** [comment]
@smartmasks
You can discuss your implementation idea in this post. Or, you can implement the code itself and send the pull request. In the latter case, you can start by looking at this commit. It is the commit that I implemented the rest of the indexing module.
https://github.com/mongo-express/mongo-express/commit/65765d0aefb85f4ae9f11f8f694db5326e70649c

If you need help with the implementation, I'd be glad to help :)

**Comment by smartmasks** [comment]
@heartnetkung 
 I have started to implement on create index. I will send pull request soon.

**Comment by dozoisch** [comment]
Fixed in #326
