### ISSUE TITLE
Binary types are converted to string

### ISSUE THREAD

**Issue by SeameX** [mongo-express/mongo-express#288]
Hello,

when i load a document (with mongo-express) e.g. id(String), name(String), picture(Binary) and i change the name and save it mongoexpress converts the binary picture into string. 

We access the mongodb via java and we are getting unmarshaling exceptions for the picture because of that. The picture is from java type "byte[]".

When i'm viewing the same document via robomongo it looks like that:
Before (written with java as byte[]):
    "logo" : { "$binary" : "base64Picture", "$type" : "00" },
After mongo-express save:
    "logo" : "base64Picture",

It would be awesome if you can fix this issue :)

Best regards

Stefan

**Comment by dozoisch** [comment]
Hi! @SeameX,

Sorry for the delay! I've made a branch with a potential fix. It seems to be working locally. Can you let me know on your side?

**Comment by SeameX** [comment]
Hello dozoisch,

thanks that works for me!

Best regards

Stefan
