### ISSUE TITLE
 npm run snyk-protect having error

### ISSUE THREAD

**Issue by panna-ahmed** [mongo-express/mongo-express#295]
After I fork and run npm install its having error on  npm run snyk-protect .

**Comment by dozoisch** [comment]
It's hard to help without knowing what kind of error you get.

**Comment by panna-ahmed** [comment]
![mongo-express](https://cloud.githubusercontent.com/assets/1288581/20862191/97dafa86-b9ce-11e6-863b-682960eeca8c.PNG)

**Comment by dozoisch** [comment]
> Snyk couldn't patch the specified vulnerabilities because GNU's patch is not available. Please install `patch`and try again.
