### ISSUE TITLE
I can delete indexes even though options.readOnly = true

### ISSUE THREAD

**Issue by hyeonsoo** [mongo-express/mongo-express#297]
I set **options.readOnly = true** in my config.js file.

Other components of writing were removed from the page as expected.

But I can still see the delete buttons on indexes section.

![image](https://cloud.githubusercontent.com/assets/15084045/21413484/ecfb142c-c83a-11e6-8e00-dcd06262f2da.png)

Please fix this.

Thank you.

**Comment by dozoisch** [comment]
Good one, will try to do it tomorrow unless someone volunteers!

**Comment by hyeonsoo** [comment]
Even though you hide buttons from the page,
What if someone manually type the URL of dropping index?
As I see the router logic, I found there's no checking of options.readOnly at all.
So anyone can even do any operations regardless of readOnly option, right?

**Comment by dozoisch** [comment]
0.34
