### ISSUE TITLE
uglify-js@2.4.24 is vulnerable

### ISSUE THREAD

**Issue by RaghavendhraK** [mongo-express/mongo-express#310]
Hi,
Please upgrade the package uglify-js from 2.4 to 2.6(i.e., mongo-express@0.35.0 > swig@1.4.2 > uglify-js@2.4.24), as the <v2.6 are vulnerable according to Node Security Project https://nodesecurity.io/advisories/48.
Thanks,
Raghu

**Comment by wulfsolter** [comment]
Please create a [Pull Request](https://help.github.com/articles/creating-a-pull-request/), this has been a known issue for 1.5 years now.

**Comment by RaghavendhraK** [comment]
Hi @wulfsolter,
Please find the pull request here https://github.com/mongo-express/mongo-express/pull/311.
Thanks,
Raghu

**Comment by dozoisch** [comment]
@RaghavendhraK Thanks for the pr!

**Comment by RaghavendhraK** [comment]
Hi @dozoisch,
Could you please also publish it to the npm. We are using mongo-express in our code, which is failing due to nsp.
Thanks,
Raghu

**Comment by dozoisch** [comment]
@RaghavendhraK I'll publish soon. Are you able to use the commit directly for the time being? I'm trying to get a set of test out before publishing. 

```
mongo-express: "mongo-express/mongo-express#4d96fe88d7c90ef034374ca90a9b63e22dd478f1"
```

**Comment by RaghavendhraK** [comment]
:+1:
