### ISSUE TITLE
Node 6 is now required?

### ISSUE THREAD

**Issue by MikeyBurkman** [mongo-express/mongo-express#313]
Is there a reason the app now has to use Node 6? We're using a PaaS that is running Node 4, and I will no longer run the latest code as a middleware anymore. Node 4 is a [supported LTS release until mid-2018](https://github.com/nodejs/LTS#lts-schedule), so this seems a bit early to require migration...

**Comment by dozoisch** [comment]
@MikeyBurkman I changed, the requirement because the code had been using features that we're not necessarily. I'll try to see if it still runs well on node 4 and put it back to 4.

**Comment by dozoisch** [comment]
If you use `9bba9a56763593830aa18c8c2eea10bd18ab032a`. It allows for node >4. Version publish will come soon. I would like to get a few more tests for routes done before version comes out.

**Comment by MikeyBurkman** [comment]
Sounds good! I was looking to fix the bug where you couldn't see the full JSON for a document in readonly mode, but I think you fixed that in the latest version. (And then when I tried running latest, I ran into the Node version issue.) So hopefully all is good after that. Thanks!
