### ISSUE TITLE
e2e tests

### ISSUE THREAD

**Issue by miherlosev** [mongo-express/mongo-express#318]
I propose to add e2e tests for basic pages: 'Home Page', 'Database View', 'Collection View' and etc. I can do this using [TestCafe](http://github.com/devexpress/testcafe).
What do you think about it?

**Comment by dozoisch** [comment]
If it works both locally and in travis, I'm all for it!

**Comment by miherlosev** [comment]
I will start to do this after fix https://github.com/mongo-express/mongo-express/issues/317

**Comment by dozoisch** [comment]
@miherlosev I don't really have a window box to test that unfortunately. It seems to be a simple fix, which is to migrate to cross-env instead of using env variables in the npm commands.

**Comment by dozoisch** [comment]
@miherlosev should be fixed now

**Comment by dozoisch** [comment]
@miherlosev I'll close this issue as it's not active anymore. Feel free to ping me to reopen
