### ISSUE TITLE
Middleware mountpath isn't correct if middleware not mounted at /

### ISSUE THREAD

**Issue by MikeyBurkman** [mongo-express/mongo-express#319]
Alright, almost everything's working. The only issue I now have is where the baseHref value trims off the last character in the URL. I've traced the issue back to [here](https://github.com/mongo-express/mongo-express/blob/master/lib/router.js#L64)

In my case, the middleware is mounted at some location, say `dbs/bar`. The `req.originalUrl` in this case is `dbs/bar`, however,  `req.url` in the router is `/`. This results in `mountPath` being `dbs/ba`, and everything gets kind of messed up.

I'll happily put in a PR for this, but I wanted to check with you first on best course of action. Maybe just remove the trailing `/` from `req.url`?

**Comment by dozoisch** [comment]
Hi!

I'm not quite sure what would be the best way to do that. Just removing the `/` might not work properly. The base url needs to be retrieved from express router. (There must be a way to retrieve mouting path.) this could then be used in the baseHref variable in layout.html.

**Comment by dozoisch** [comment]
closed #320
