### ISSUE TITLE
Commnad 'npm run start' fails if local machine doesn't have local instance of a mongoDb

### ISSUE THREAD

**Issue by miherlosev** [mongo-express/mongo-express#322]
![Error](https://cloud.githubusercontent.com/assets/4133518/23352771/27780c62-fcda-11e6-9a21-13bd51b5edaf.png)

**Comment by dozoisch** [comment]
Have you change the hostname in the config?

**Comment by dozoisch** [comment]
Without more information, I'll just close this issue. Feel free to ping me to reopen!
