### ISSUE TITLE
run at boot

### ISSUE THREAD

**Issue by MaikoHermans** [mongo-express/mongo-express#323]
Is there a way to run a command like
`mongo-express -a -u superuser -p password`

on boot for ubuntu?
I tried setting it in the crontab as well as making a conf for it in `/etc/init`
but neither did work

I was hoping there was a way to make sure the interface runs at all times

**Comment by dozoisch** [comment]
Well normally /etc/init should work, so it's most likely an issue in the configuration. 

You can also try using something like PM2 or supervisor to handle this for you.
