### ISSUE TITLE
DB and collection name are too restrictive

### ISSUE THREAD

**Issue by abellion** [mongo-express/mongo-express#327]
I tried a name with a dash and it doesn't work as the message says : "Database names must begin with a letter or underscore, and can contain only letters, numbers, underscores and dots."

From the doc, it's allowed to use a dash : https://docs.mongodb.com/manual/reference/limits/#naming-restrictions

**Comment by MikeyBurkman** [comment]
Looks like it should be a pretty quick fix to the regex here: https://github.com/mongo-express/mongo-express/blob/master/lib/routes/database.js#L62

I assume you'd just go with the more restrictive Windows rules, since there's no way (I think?) of knowing which platform mongo is running on.

**Comment by dozoisch** [comment]
@MikeyBurkman @abellion Created a Pr to fix that. Let me know what you think

**Comment by rayfoss** [comment]
on 0.44 I still can't create anything with a dash in it

**Comment by dozoisch** [comment]
@rayfoss I will need more info than that because I just did it and it worked. Are you getting errors etc?

![image](https://user-images.githubusercontent.com/4422516/33636076-85f4d9f0-d9cf-11e7-8432-49e303ed8834.png)
