### ISSUE TITLE
Uncaught TypeError: s.default.set_show_to_level is not a function

### ISSUE THREAD

**Issue by asantiago** [mongo-express/mongo-express#331]
Hello,

when enter in the collections of my db, the next error happen:

> Uncaught TypeError: s.default.set_show_to_level is not a function

After when click on any document this error happen every time:

> Uncaught ReferenceError: loadDocument is not defined

I have been looking for something similar in the issues but i didn't found anything. Also I had upgraded the project to the last version, and still happen.

Thank you for the project.

**Comment by hod-shcraigen** [comment]
Exact same issue.

**Comment by dozoisch** [comment]
@asantiago @hod-shcraigen What version do you have checked out? Normally the project should ship with the built dependency starting v0.37.1.

**Comment by toddpratt** [comment]
So, the work-around above seems to temporarily solve the problem, but even with a fresh npm -g install mongo-express, the GUI is broken (same browser-side exceptions described above).

**Comment by heartnetkung** [comment]
duplicate with #330

**Comment by dozoisch** [comment]
Fixed in v0.39.2 sorry about that.
