### ISSUE TITLE
npm crashes by running 

### ISSUE THREAD

**Issue by smallgiant2005** [mongo-express/mongo-express#334]
I am running latest npm 7.9.0 on windows 7 x64 and tried to run installation command:
 
npm run start-dev

but it crashes. Here is the log:

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'start-dev' ]
2 info using npm@4.2.0
3 info using node@v7.9.0
4 verbose run-script [ 'prestart-dev', 'start-dev', 'poststart-dev' ]
5 info lifecycle mongo-express@0.39.2~prestart-dev: mongo-express@0.39.2
6 silly lifecycle mongo-express@0.39.2~prestart-dev: no script for prestart-dev, continuing
7 info lifecycle mongo-express@0.39.2~start-dev: mongo-express@0.39.2
8 verbose lifecycle mongo-express@0.39.2~start-dev: unsafe-perm in lifecycle true
9 verbose lifecycle mongo-express@0.39.2~start-dev: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\wwwroot\mongo-express\node_modules\.bin;C:\Program Files\nodejs\;C:\Users\NAV\AppData\Roaming\npm
10 verbose lifecycle mongo-express@0.39.2~start-dev: CWD: C:\wwwroot\mongo-express
11 silly lifecycle mongo-express@0.39.2~start-dev: Args: [ '/d /s /c',
11 silly lifecycle   'concurrently --kill-others "nodemon app" "npm run build-dev"' ]
12 silly lifecycle mongo-express@0.39.2~start-dev: Returned: code: 1  signal: null
13 info lifecycle mongo-express@0.39.2~start-dev: Failed to exec start-dev script
14 verbose stack Error: mongo-express@0.39.2 start-dev: `concurrently --kill-others "nodemon app" "npm run build-dev"`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:194:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:194:7)
14 verbose stack     at maybeClose (internal/child_process.js:899:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid mongo-express@0.39.2
16 verbose cwd C:\wwwroot\mongo-express
17 error Windows_NT 6.1.7601
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "start-dev"
19 error node v7.9.0
20 error npm  v4.2.0
21 error code ELIFECYCLE
22 error errno 1
23 error mongo-express@0.39.2 start-dev: `concurrently --kill-others "nodemon app" "npm run build-dev"`
23 error Exit status 1
24 error Failed at the mongo-express@0.39.2 start-dev script 'concurrently --kill-others "nodemon app" "npm run build-dev"'.
24 error Make sure you have the latest version of node.js and npm installed.
24 error If you do, this is most likely a problem with the mongo-express package,
24 error not with npm itself.
24 error Tell the author that this fails on your system:
24 error     concurrently --kill-others "nodemon app" "npm run build-dev"
24 error You can get information on how to open an issue for this project with:
24 error     npm bugs mongo-express
24 error Or if that isn't available, you can get their info via:
24 error     npm owner ls mongo-express
24 error There is likely additional logging output above.
25 verbose exit [ 1, true ]
```

**Comment by dozoisch** [comment]
Can you try running `nodemon app` and `npm run build-dev` separately to see if they run properly?

**Comment by smallgiant2005** [comment]
nodemon app gives this message:
'nodemon' is not recognized as an internal or external command,
operable program or batch file.


and the second one gives these errors:
C:\wwwroot\mongo-express>npm run build-dev

> mongo-express@0.39.2 build-dev C:\wwwroot\mongo-express
> webpack --watch

clean-webpack-plugin: C:\wwwroot\mongo-express\build has been removed.

Webpack is watching the files.

(node:9208) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
[copy-webpack-plugin] WARNING - unable to locate 'C:\wwwroot\mongo-express\node_modules\codemirror\package.json/lib/codemirror.css' at 'C:\wwwroot\mongo-express\node
_modules\codemirror\package.json/lib/codemirror.css'
[copy-webpack-plugin] WARNING - unable to locate 'C:\wwwroot\mongo-express\node_modules\bootstrap\package.json/dist/css/bootstrap.min.css' at 'C:\wwwroot\mongo-expre
ss\node_modules\bootstrap\package.json/dist/css/bootstrap.min.css'
[copy-webpack-plugin] WARNING - unable to locate 'C:\wwwroot\mongo-express\node_modules\bootstrap\package.json/dist/css/bootstrap.min.css.map' at 'C:\wwwroot\mongo-e
xpress\node_modules\bootstrap\package.json/dist/css/bootstrap.min.css.map'
[copy-webpack-plugin] WARNING - unable to locate 'C:\wwwroot\mongo-express\node_modules\bootstrap\package.json/dist/css/bootstrap-theme.min.css' at 'C:\wwwroot\mongo
-express\node_modules\bootstrap\package.json/dist/css/bootstrap-theme.min.css'
[copy-webpack-plugin] WARNING - unable to locate 'C:\wwwroot\mongo-express\node_modules\bootstrap\package.json/dist/css/bootstrap-theme.min.css.map' at 'C:\wwwroot\m
ongo-express\node_modules\bootstrap\package.json/dist/css/bootstrap-theme.min.css.map'
Hash: 1e7d83cb3ebb7426cc01
Version: webpack 2.4.1
Time: 1224ms
                     Asset       Size  Chunks                    Chunk Names
                 vendor.js     345 kB       6  [emitted]  [big]  vendor
             codemirror.js     390 kB       0  [emitted]  [big]  codemirror
                  index.js    1.63 kB       2  [emitted]         index
                 gridfs.js  294 bytes       3  [emitted]         gridfs
               document.js    1.94 kB       4  [emitted]         document
               database.js    1.66 kB       5  [emitted]         database
             collection.js    20.9 kB       1  [emitted]         collection
img/mongo-express-logo.svg    1.44 kB          [emitted]
             img/gears.gif    50.3 kB          [emitted]
 img/mongo-express-logo.ai     386 kB          [emitted]  [big]
img/mongo-express-logo.png    17.8 kB          [emitted]
           img/favicon.ico    17.8 kB          [emitted]
             css/style.css    1.84 kB          [emitted]
   [0] ./~/jquery/dist/jquery.js 268 kB {6} [built]
   [1] ./lib/scripts/codeMirrorLoader.js 367 bytes {0} [built]
   [2] ./~/codemirror/lib/codemirror.js 359 kB {0} [built]
   [3] ./lib/scripts/jQueryLoader.js 239 bytes {6} [built]
   [4] ./~/bootstrap/dist/js/npm.js 484 bytes {6} [built]
   [5] ./~/codemirror/mode/javascript/javascript.js 31.1 kB {0} [built]
   [6] ./~/renderjson/renderjson.js 11.3 kB {1} [built]
   [7] ./lib/scripts/collection.js 9.3 kB {1} [built]
   [8] ./lib/scripts/database.js 1.55 kB {5} [built]
   [9] ./lib/scripts/document.js 1.83 kB {4} [built]
  [10] ./lib/scripts/gridfs.js 186 bytes {3} [built]
  [11] ./lib/scripts/index.js 1.52 kB {2} [built]
  [12] ./lib/scripts/vendor.js 64 bytes {6} [built]
  [13] ./~/bootstrap/js/affix.js 4.84 kB {6} [built]
  [19] ./~/bootstrap/js/modal.js 9.99 kB {6} [built]
    + 10 hidden modules

ERROR in [copy-webpack-plugin] unable to locate 'C:\wwwroot\mongo-express\node_modules\codemirror\package.json/lib/codemirror.css' at 'C:\wwwroot\mongo-express\node_
modules\codemirror\package.json/lib/codemirror.css'

ERROR in [copy-webpack-plugin] unable to locate 'C:\wwwroot\mongo-express\node_modules\bootstrap\package.json/dist/css/bootstrap.min.css' at 'C:\wwwroot\mongo-expres
s\node_modules\bootstrap\package.json/dist/css/bootstrap.min.css'

ERROR in [copy-webpack-plugin] unable to locate 'C:\wwwroot\mongo-express\node_modules\bootstrap\package.json/dist/css/bootstrap.min.css.map' at 'C:\wwwroot\mongo-ex
press\node_modules\bootstrap\package.json/dist/css/bootstrap.min.css.map'

ERROR in [copy-webpack-plugin] unable to locate 'C:\wwwroot\mongo-express\node_modules\bootstrap\package.json/dist/css/bootstrap-theme.min.css' at 'C:\wwwroot\mongo-
express\node_modules\bootstrap\package.json/dist/css/bootstrap-theme.min.css'

ERROR in [copy-webpack-plugin] unable to locate 'C:\wwwroot\mongo-express\node_modules\bootstrap\package.json/dist/css/bootstrap-theme.min.css.map' at 'C:\wwwroot\mo
ngo-express\node_modules\bootstrap\package.json/dist/css/bootstrap-theme.min.css.map'

**Comment by dozoisch** [comment]
you probably have to run it from your node_modules like `./node_modules/.bin/nodemon app`

else you can also just do `node app.js`
