### ISSUE TITLE
html escaping of sub documents

### ISSUE THREAD

**Issue by BDav24** [mongo-express/mongo-express#335]
Hi, html escaping does not work for sub documents:

```
{
  "key1": "<script>window.alert('alert 1!')</script>", // escaped
  "key2": {"subkey": "<script>window.alert('alert 2!')</script>"} // not escaped
}
```

I guess https://github.com/mongo-express/mongo-express/blob/master/lib/filters.js#L131 should be something like:
```
return '<pre>' + entifyGTLTAmp(JSON.stringify(input, null, 2)) + '</pre>';
```

Thanks!

**Comment by dozoisch** [comment]
Or maybe we could do this: 

```
  function replacer(key, value) {
    if (typeof value === 'string ') {
      return entifyGTLTAmp(string);
    };
    return value;
  }
  return '<pre>' + JSON.stringify(input, replacer, 2) + '</pre>';
```

**Comment by BDav24** [comment]
Yes, either solution works.

(just one typo: 'string ' => 'string')

**Comment by dozoisch** [comment]
I'll try to fix it this Saturday.

**Comment by BDav24** [comment]
@dozoisch Thanks :)

**Comment by dozoisch** [comment]
@BDav24 I'll cut a new release when I merge my branch for db names.

**Comment by BDav24** [comment]
Ok thanks, no hurry on my side.
