### ISSUE TITLE
How to connect to multiple databases?

### ISSUE THREAD

**Issue by ggiacomo** [mongo-express/mongo-express#336]
How to setup config.js in order to connect to multiple databases?
Thank you.

**Comment by dozoisch** [comment]
@wulfsolter maybe you know about that!

**Comment by ggiacomo** [comment]
Ok, I started read all the comments in the config.js file, and found the variable
ME_CONFIG_MONGODB_ENABLE_ADMIN than need to be set to true :)
Thank you!

**Comment by sydneywu** [comment]
I was able to do it by adding a -a in the command.
$ mongo-express -p pass -u user -a

**Comment by pavelgronsky** [comment]
Ok, but how I can ran one mongo-express container for fer mongo database container in docker-compose?
