### ISSUE TITLE
Cannot find module '../build-assets.json'

### ISSUE THREAD

**Issue by antoniogiordano** [mongo-express/mongo-express#341]
I receive this error Cannot find module '../build-assets.json' after "npm i" & "npm run start" on an Ubuntu machine (16.04).
Node version: 7.8.0
Npm: 4.2.0

**Comment by dozoisch** [comment]
@antoniogiordano How did you install the the module? If you clone the repo, please run `npm run build`

**Comment by antoniogiordano** [comment]
It works, thanks!

**Comment by vicatcu** [comment]
@dozoisch same question on apache.... any idea what's worng with this Location block?

```
   <Location /mongo>
      ProxyPass http://127.0.0.1:8081
      ProxyPassReverse http://1127.0.0.1:8081
   </Location>
```

Home page loads but no assets come along for the ride.

**Comment by olawalejuwonm** [comment]
i install the module using yarn and I'm getting the error

**Comment by rtritto** [comment]
@olawalejuwonm you should first do a build

**Comment by olawalejuwonm** [comment]
I'm running this using mongo-express not in development

**Comment by rtritto** [comment]
Use `npm run build` then `npm start`

**Comment by olawalejuwonm** [comment]
from which path?
It was installed globally

**Comment by rtritto** [comment]
> from which path?

Run `npm root -g`

**Comment by olawalejuwonm** [comment]
how do i get for yarn

**Comment by rtritto** [comment]
`yarn global dir`

**Comment by olawalejuwonm** [comment]
@rtritto 
![image](https://github.com/mongo-express/mongo-express/assets/52759812/7f9993fa-c111-4f5c-8116-8748f789172b)

I'm getting that

**Comment by olawalejuwonm** [comment]
npm start also give the same error
![image](https://github.com/mongo-express/mongo-express/assets/52759812/a758b0ef-57a6-4b3e-9e19-f2be0cccfb2f)

**Comment by antoniogiordano** [comment]
sorry I'm not a Windows user @olawalejuwonm

**Comment by rtritto** [comment]
> @rtritto ![image](https://user-images.githubusercontent.com/52759812/260850573-7f9993fa-c111-4f5c-8116-8748f789172b.png)
> 
> I'm getting that

You can install globally https://www.npmjs.com/package/win-node-env: `npm add win-node-env -g`

> @rtritto @dozoisch @antoniogiordano i need help please. I tried setting .env when i run nom run build I got ![image](https://user-images.githubusercontent.com/52759812/261326050-357a3d64-ae09-47cd-a2ea-8a2c1e94a1d4.png)
> 
> I run npm install then npm run build again I got ![image](https://user-images.githubusercontent.com/52759812/261326437-89c3ea08-dc2c-481f-abcb-a661c1ae7512.png)
> 
> Help please!

Run first `npm i`

**Comment by olawalejuwonm** [comment]
I run npm install and still got that
