### ISSUE TITLE
Error on startup: `mongo.Connection` is undefined

### ISSUE THREAD

**Issue by mattcollier** [mongo-express/mongo-express#355]
Just did a fresh install on master commit: 0787572106b4dd4d7bfb678564322ebc9ee6f982

https://github.com/mongo-express/mongo-express/blob/master/lib/db.js#L179

I can get rolling by changing to:
```javascript
let port = config.mongodb.port    || 27017;`
```

EDIT: I'm using mongo v2.6.12 and node v8.2.1

**Comment by dozoisch** [comment]
I'll check it this weekend.

**Comment by dozoisch** [comment]
Fixed in v0.42.2
