### ISSUE TITLE
Feature Request: Connection String URI Format

### ISSUE THREAD

**Issue by boustanihani** [mongo-express/mongo-express#356]
Please allow passing the "**Connection String URI Format**" instead of separate params...

`mongodb://[username:password@]host1[:port1][,host2[:port2],...[,hostN[:portN]]][/[database][?options]]`

Check => https://docs.mongodb.com/manual/reference/connection-string/

**Comment by dozoisch** [comment]
It is allowed since https://github.com/mongo-express/mongo-express/blob/master/HISTORY.md#0420---thu-jul-20-2017

**Comment by rayfoss** [comment]
When using uri's
If you get an error such as:
```
/usr/local/lib/node_modules/mongo-express/node_modules/mongodb/lib/mongo_client.js:336
          throw err
          ^
MongoError: seed list contains no mongos proxies, replicaset connections requires the parameter replicaSet to be supplied in the URI or options object, mongodb://server:port/db?replicaSet=name
    at connectCallback (/usr/local/lib/node_modules/mongo-express/node_modules/mongodb/lib/mongo_client.js:422:23)
```

you probably need to quote the url, as the ampersands get interpreted as terminal tmux/sleep
