### ISSUE TITLE
Running mongo express under Passenger

### ISSUE THREAD

**Issue by r-a-c** [mongo-express/mongo-express#358]
Hello. 

Is it possible to run this app under Phusion Passenger ?  I have configured the connectionString and i am getting this log:

App 999831 stderr: /my/path/nodejs/mexpress/node_modules/mongodb/lib/mongo_client.js:367
App 999831 stderr:             throw err
App 999831 stderr:             ^
App 999831 stderr: 
App 999831 stderr: TypeError: db is not a function
App 999831 stderr:     at /my/path/nodejs/mexpress/lib/db.js:114:53

In the mongo log i can  see succesful logs  from the app
mongodb 3.4 and nodejs v6.9.0
passenger 5.1.5

**Comment by wulfsolter** [comment]
https://github.com/mongo-express/mongo-express/blob/master/lib/db.js#L193-L197

`db` should be the database handler. 

If `db` is null / undefined, then there is no valid connection to the database. Check your settings.

**Comment by dozoisch** [comment]
https://github.com/mongo-express/mongo-express/pull/366 should fixed the issue and has been published as v0.42.3

**Comment by SleepyDeb** [comment]
@rtritto close this
