### ISSUE TITLE
Azure CosmosDB

### ISSUE THREAD

**Issue by ariuschen** [mongo-express/mongo-express#359]
Does it support Azure CosmosDB ?
I am using CosmosDB with Mongodb API while error occurs after trying to view databases.

**Comment by dozoisch** [comment]
Without more information about the errors it's hard to say. I'm not sure anyone ever tried with CosmosDB. We're open to pull requests to improve support.

**Comment by diberry** [comment]
@dozoisch I would like to help with this request if possible - I'm also trying to get this to work with Mongo on CosmosDB. I would like to use it from the container.

The connection string looks like:

mongodb://diberry-mongodb-cosmos:SECRET@diberry-mongodb-cosmos.mongo.cosmos.azure.com:10255/?ssl=true&replicaSet=globaldb&retrywrites=false&maxIdleTimeMS=120000&appName=@MY-RESOURCE-NAME@

I'm trying to pass that into the container (with variables replaced) and the container defaults to local host. I'm trying to get the cloned repo to work but build fails on Windows becauase of the bootstrap fonts: 

> cross-env NODE_ENV=production webpack

[webpack-cli] Compilation finished
assets by status 1.51 MiB [cached] 18 assets
runtime modules 3.29 KiB 4 modules
orphan modules 111 bytes [orphan] 1 module
modules by path ./node_modules/ 791 KiB
  modules by path ./node_modules/bootstrap/ 73.6 KiB 13 modules
  modules by path ./node_modules/codemirror/ 425 KiB
    ./node_modules/codemirror/lib/codemirror.js 389 KiB [built] [code generated]
    ./node_modules/codemirror/mode/javascript/javascript.js 37 KiB [built] [code generated]
  ./node_modules/jquery/dist/jquery.js 281 KiB [built] [code generated]
  ./node_modules/renderjson/renderjson.js 10.8 KiB [built] [code generated]
modules by path ./lib/scripts/ 14.6 KiB 7 modules

LOG from copy-webpack-plugin
<e> unable to locate "C:\repos\databases\mongo-express\node_modules\codemirror\theme\*" at "C:\repos\databases\mongo-express\node_modules\codemirror\theme\*"
<e> unable to locate "C:\repos\databases\mongo-express\node_modules\bootstrap\dist\fonts\*" at "C:\repos\databases\mongo-express\node_modules\bootstrap\dist\fonts\*"
+ 108 hidden lines

ERROR in unable to locate "C:\repos\databases\mongo-express\node_modules\codemirror\theme\*" at "C:\repos\databases\mongo-express\node_modules\codemirror\theme\*"

ERROR in unable to locate "C:\repos\databases\mongo-express\node_modules\bootstrap\dist\fonts\*" at "C:\repos\databases\mongo-express\node_modules\bootstrap\dist\fonts\*"

webpack 5.3.2 compiled with 2 errors in 11156 ms
npm ERR! code 1
npm ERR! path C:\repos\databases\mongo-express
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c "cross-env NODE_ENV=production webpack"

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\diberry\AppData\Local\npm-cache\_logs\2021-02-01T23_01_33_949Z-debug.log
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
