### ISSUE TITLE
read only ui

### ISSUE THREAD

**Issue by wavelet123** [mongo-express/mongo-express#365]
Hi,
We want to use mongo-express as a read only web ui for developers,can we disable the reIndex in the page?

Thanks

**Comment by wavelet123** [comment]
And for a replica set,can we connect to the slave with rs.slaveOk=true?

Thanks

**Comment by dozoisch** [comment]
https://github.com/mongo-express/mongo-express/blob/master/config.default.js#L131-L132

**Comment by wavelet123** [comment]
And can we limit the export size?
We dont'want the developers to export all the documents.

Thanks.

**Comment by dozoisch** [comment]
That is not possible right now, but we do accept contributions!
