### ISSUE TITLE
Accessing documents with BinData as value for `_id`

### ISSUE THREAD

**Issue by riker09** [mongo-express/mongo-express#367]
Hello there. I'm new to MongoDB and C#, so please don't frown when this is a stupid question. But I'm unable to access documents in the web client where the value for the `_id` column (property?) was generated from a C# `Guid`.

Here's my (simplified) C# class:

```csharp
    public class MyClass
    {
        [BsonId]
        public Guid MyId {get; set; }

        public string MyPropertyA { get; set; }
    }
```

Now when I store a document:

```csharp
var myClassObj = new MyClass
{
    MyId = Guid.NewGuid(), // Let's assume it is "C56A4180-65AA-42EC-A945-5FD21DEC0538"
    MyPropertyA = "Foo"
}
await mongoClient.SaveDocument(myClassObj.ToBsonDocument());
```

This is what ends up in the mongo database (retrieved with mongo cli):
```javascript
{ "_id" : BinData(3,"gEFqxapl7EKpRV/SHewFOA=="), "MyPropertyA": "Foo" }
```

This is what is rendered in the collection view:

![mongodb guid error](https://user-images.githubusercontent.com/568497/30693054-3512ab8e-9ece-11e7-9ad9-bc4aa78304ac.PNG)

And I cannot open the document. The error message is `Document not found!`.

I'm not sure if this is an error with mongo, mongo-express or C# Guids. I'm still learning and would appreciate some insights.

> Issue was first (mistakingly) reported here: https://github.com/mongo-express/mongo-express-docker/issues/5

**Comment by heartnetkung** [comment]
Mongo-express does not support binary id. Though what you're doing is a little weird. 

Normally, the _id field is either number, string, or MongoID. Use number or string if you really need to specify your primary unique key (such as when you import your data from elsewhere), and use default MongoID otherwise (insert your data without _id field).

Hope it helps.

**Comment by riker09** [comment]
So what you're saying is that my data has a Guid ID and I cannot use that as a primary key, is that it? Instead I should let Mongo choose an ID by itself and store my ID in another field. And if I ever need to retrieve my data by (my) primary key just do a search on my ID field? Okay, will do so.

It just feels a little bit weird to me, as well. Mongo seems to be just fine with a Binary ID as PK. Judging from my point of view it seems like missing feature in mongo-express. But I can live with that since mongo-express is supposed to be a debugging tool after all. :slightly_smiling_face:

**Comment by dozoisch** [comment]
@riker09 it shouldn't be too hard to add the support for the BinData. I unfortunately don't really have the bandwidth right now to do it, but if you have time to dive in and do a PR, I'll get it deployed!

**Comment by heartnetkung** [comment]
@riker09 I misunderstood your intention. I agree, you should keep your primary key if you already have one and use it as mongodb primary key.

**Comment by riker09** [comment]
I tried to give it a shot, but unfortunately I didn't get very far. I assume one would need to

a) come up with a serialization that takes BinData into account when rendering the table rows
b) find a way to retrieve records with BinData as PK (I assume this is done in `lib/router.js`?)

**Comment by dozoisch** [comment]
Yes! 

Exactly, need to fix serialization for it, and then probably need to add a type in the dropdown of view collection so that you can select BinData (instead of ObjectID)

and then make sure that it can be retrieved

**Comment by riker09** [comment]
I think I have a solution, but I cannot create a commit since a Git Hook throws errors. I'm not familiar with this concept (git hooks). How can I create a PR?

**Comment by dozoisch** [comment]
@riker09  what error is it throwing? 

You can commit with `git commit -n` to skip the hook.

**Comment by dozoisch** [comment]
@riker09  you should also be able to create a PR from your fork https://github.com/mongo-express/mongo-express/compare/master...riker09:master

(It is normal that you can't push on the main repo)

**Comment by riker09** [comment]
He, `git commit -n`. Never knew about that before.

**Comment by dozoisch** [comment]
I'll check your pr on saturday

**Comment by dozoisch** [comment]
Published as 0.43.0! Sorry about delay! :)

**Comment by damien-malescot** [comment]
Hi, 

I'm using mongo-express 0.49 with BinData as _id

```
public class MessageDocument {
    @Id
    private UUID id;
    ...
}
```

Document's id appears as **NgBAG0rmT+uDo6K/gkhfCw==** in GUI but when i want to view document, it's a ... 404 document not found :\

Same issue as here ?

**Comment by dozoisch** [comment]
make sure your ID is url encoded => https://meyerweb.com/eric/tools/dencoder/

**Comment by damien-malescot** [comment]
Just try with BinData 3 (Legacy UUID in java driver) and it's OK.
When i put BinData 4 (Standard UUID in java driver) i got a 404 not found

Maybe there is mistake somewhere which encode only bindata 3 ?

**Comment by damien-malescot** [comment]
@dozoisch push a MR : #473
If you can merge it as soon as possible thx ;)

**Comment by shadowbane1000** [comment]
As of today, I am still having issues with BinData 4.  Any news on a fix?
