### ISSUE TITLE
Not an Issue just a question

### ISSUE THREAD

**Issue by r1nky** [mongo-express/mongo-express#370]
Hi,

Been looking at mongo-express and cannot see where i can enable authentication on data base.

We would not want to hard code our passwords into config.js.

Is this possible. Compared to Genghis, it prompts you for user name, password and url for remote data base on web interface. Would this be possible on mongo express and if not will  it be a feature in the near future?

**Comment by r1nky** [comment]
I found:

https://github.com/es92/mongo-express-auth

But not sure what it does as yet

**Comment by dozoisch** [comment]
@r1nky we're open to pull requests! This project is entirely driven by its users.
