### ISSUE TITLE
Cant scroll When Adding a new Document

### ISSUE THREAD

**Issue by iamabjain** [mongo-express/mongo-express#376]
When we add a new Doument and while typing that, When the no. of lines exceeds 16, it should be SCROLLABLE but it isnt.
CAN I start working on this issue?
I can solve it.

**Comment by dozoisch** [comment]
For sure! I'll be happy to review the pr :)

**Comment by kunal-relan** [comment]
I see the issue is still open, is this already fixed or shall I try fixing this?

**Comment by dozoisch** [comment]
@kunal-relan I think this is still a problem.

**Comment by feriat** [comment]
Hi! @dozoisch @kunal-relan @iamabjain any luck on scroll issue for adding new Documents?

**Comment by ayushcher1308** [comment]
I have solved it in my pc...Can I pull request.

**Comment by dozoisch** [comment]
@ayushcher1308 I'll be happy to review a PR!
