### ISSUE TITLE
Proposal: Add VCAP_APP_PORT to readme

### ISSUE THREAD

**Issue by githubsaturn** [mongo-express/mongo-express#377]
Hi,
I am the maintainer of [Project CaptainDuckDuck](https://github.com/githubsaturn/captainduckduck), and I am in the processe of implementing popular built-in docker images into the webserver package as one-click apps.

I would like to add mongo-express to the list. But the port number is hardcoded as 8081 and the environmental variable controlling it (`VCAP_APP_PORT`) is not listed in readme under environmental variables, which makes me think the maintainers do not want to expose this value? Is there any reason for doing so?

**Comment by dozoisch** [comment]
@githubsaturn I don't have the knowledge about the reason, since it's way before my time. But I'm all for you adding it.
