### ISSUE TITLE
User Managment via Passport.JS

### ISSUE THREAD

**Issue by BetaStacks** [mongo-express/mongo-express#383]
Is it possible to only allow access to certain views based on the group the user is in? ie. I would only like admins to have access to the database view.

**Comment by dozoisch** [comment]
Currently it's not a feature that is supported. I'll be happy to review a PR if you want to implement it, but this is not something I can do given the bandwidth I have right now.

**Comment by BetaStacks** [comment]
Awesome, I will start working on. Thank you.
