### ISSUE TITLE
npm install errors out

### ISSUE THREAD

**Issue by BetaStacks** [mongo-express/mongo-express#384]
Every time I try to install I get the following error

root@raspberrypi:/home/pi/node-apps/mongo-express# npm install
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
npm ERR! code 128
npm ERR! Command failed: /usr/bin/git clone --depth=1 -q -b master git://github.com/dozoisch/renderjson.git /root/.npm/_cacache/tmp/git-clone-b9b92fdb
npm ERR! fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-b9b92fdb': Permission denied
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-01-11T04_29_12_934Z-debug.lo

**Comment by dozoisch** [comment]
that seems to be a permission issue on your side. It's trying to install something under root/.npm and can't.

**Comment by dozoisch** [comment]
I'll close this issue as there was no answer. Feel free to ping for reopen with more information.
