### ISSUE TITLE
export query result

### ISSUE THREAD

**Issue by scne** [mongo-express/mongo-express#385]
Is it possible to export query result on collection?

**Comment by wulfsolter** [comment]
PRs are very welcome :) Should be pretty straightforward to implement.

**Comment by MikeyBurkman** [comment]
This was implemented in #388, will be in the next release.

**Comment by aogilvie** [comment]
Is this implemented for export .csv?
When ever I run a query and hit export .csv it exports the entire collection :(

mongo 4.0.1
docker image latest

**Comment by gozn** [comment]
any update? latest version still can't export

**Comment by rtritto** [comment]
@gozn this is working on the v1.1.0-rc-3
