### ISSUE TITLE
invalid csrf token

### ISSUE THREAD

**Issue by ariuschen** [mongo-express/mongo-express#386]
Hi,

I encountered an "invalid csrf token" issue when "readOnly" was set to true in config.js.
What I wanted to do is just to set every document to read only, while the following error occurs after clicking the back button in the document.html page.

**This back button pushed!**
![image](https://user-images.githubusercontent.com/7312908/34928165-0c901ee4-f9ff-11e7-86db-e4c44937b41a.png)

**Error occurs!**
![image](https://user-images.githubusercontent.com/7312908/34928069-6663884e-f9fe-11e7-99a1-1bc571505c87.png)

I noticed that the onclick event functions are different according to the read only value, but still work on it.

**Comment by vicatcu** [comment]
I'm getting this when I try and create a document.

**Comment by PHPHa** [comment]
Just look this #412

**Comment by beatgrabe** [comment]
Still on `0.49.0`
