### ISSUE TITLE
NaN and Infinity are displayed as null in document edition

### ISSUE THREAD

**Issue by jeromevalentin** [mongo-express/mongo-express#391]
Through the mongo-express web interface when editing a document stored in mongo I get the display below:
```javascript
{
    "_id": "test",
    "inf": null,
    "minf": null,
    "nan": null,
    "array": [
       12.05,
        null,
        458,
        null,
        14523,
        12.4538,
        null
    ]
}
```
While the real object stored in database is containing:
```javascript
{
    "_id": "test",
    "inf": Infinity,
    "minf": -Infinity,
    "nan": NaN,
    "array": [
       12.05,
        NaN,
        458,
        Infinity,
        14523,
        12.4538,
        -Infinity
    ]
}
```
I know the second representation is not a valid JSON one, but displaying null for those fields is also not valid. Might it be possible to display Infinity/-Infinity/NaN as string instead of null? (the representation will still be wrong, but we may be able to distinguish the different cases)

**Comment by dozoisch** [comment]
@jeromevalentin this is probably a bug with the custom jsonifier. I'll try to take a look this weekend
