### ISSUE TITLE
Disabling Export feature

### ISSUE THREAD

**Issue by majidpal** [mongo-express/mongo-express#392]
Is there a way to disable export feature on UI so that developers dont click it. Because it crashes mongo-express container while exporting it.

**Comment by dozoisch** [comment]
The setting `read_only` currently disables the export buttons (https://github.com/mongo-express/mongo-express/blob/master/lib/views/collection.html#L343) but also disable edition of document. If you want to do a pr that adds a new setting to disable the export buttons only, I'm open for that!

**Comment by majidpal** [comment]
I would like to try this. So what setting i will have to do?

**Comment by dozoisch** [comment]
It could be something a bit like the [`confirmDelete`](https://github.com/mongo-express/mongo-express/blob/master/config.default.js#L148), but named `disableExports` ?

**Comment by majidpal** [comment]
Thanks hugo. But I want to try with read_only first and see if it serves
purpose. because we are not using mongo express for editing document. Where
should i do the changes?

**Comment by dozoisch** [comment]
@majidpal depending on how you use mongo-express there are different ways. The simplest way is to have your own config.js and set options.readOnly to false (here: https://github.com/mongo-express/mongo-express/blob/master/config.default.js#L132)

**Comment by majidpal** [comment]
I had that setting set as false earlier but still it was showing me export
button. I tried setting true and bouncing container. But still it is
showing me export button.

    //readOnly: if readOnly is true, components of writing are not visible.
    readOnly: true,

**Comment by MikeyBurkman** [comment]
@dozoisch The readonly flag only affects the size of the icons. (The icons are larger if readonly because you don't need to fit the compact/delete buttons.) Which makes sense -- I would fully expect you to be able to export from a readonly view :)

**Comment by dozoisch** [comment]
Oh true that, I looked to fast (Thanks @MikeyBurkman). Will require a new setting then @majidpal

**Comment by MikeyBurkman** [comment]
Also, @majidpal the exporting should work just fine if they do the standard export, as that one streams data as it reads from the DB. The other two load the entire result into memory before serializing them and sending them back to the client, so those will definitely crash with large datasets. Maybe the setting should only apply to those export options?

**Comment by majidpal** [comment]
Where can I change the export settings? In my current setup, it tries to
export entire database. It would be good to have disable export settings.

**Comment by majidpal** [comment]
@Michael - Have not done any changes related to output in config. We are
using standard export button. Is there any way to control export?
