### ISSUE TITLE
Problems with doker.

### ISSUE THREAD

**Issue by luizpaulofranz** [mongo-express/mongo-express#397]
Hi, I'm new with docker and I'm trying to access my mongo db which was created with oficial docker image, so I'm trying to link one container to the other with this command:

`docker run -it --rm -p 8081:8081 --link myMongo:myMongo mongo-express`

But I'm getting this error:

```
Mongo Express server listening at http://0.0.0.0:8081
Server is open to allow connections from anyone (0.0.0.0)
basicAuth credentials are "admin:pass", it is recommended you change this in your config.js!

/node_modules/mongodb/lib/server.js:265
        process.nextTick(function() { throw err; })
                                      ^
MongoError: failed to connect to server [mongo:27017] on first connect
    at Pool.<anonymous> (/node_modules/mongodb-core/lib/topologies/server.js:326:35)
    at emitOne (events.js:116:13)
    at Pool.emit (events.js:211:7)
    at Connection.<anonymous> (/node_modules/mongodb-core/lib/connection/pool.js:270:12)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at Connection.emit (events.js:214:7)
    at Socket.<anonymous> (/node_modules/mongodb-core/lib/connection/connection.js:175:49)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
```

Any idea why it is happend? Thanks in advance.

**Comment by dozoisch** [comment]
Seems like it can't connect to the mongo db server. ` failed to connect to server [mongo:27017] on first connect`. Make sure that the host & port are accurate in the config.js OR env variables.

**Comment by knickers** [comment]
Make the second option in the `link` parameter to `mongo`.

```--link myMongo:mongo```

**Comment by dozoisch** [comment]
Will close this issue as it's not  been active in a long time. Feel free to ping me for reopening.

**Comment by crossSulation** [comment]
> Hi, I'm new with docker and I'm trying to access my mongo db which was created with oficial docker image, so I'm trying to link one container to the other with this command:
> 
> `docker run -it --rm -p 8081:8081 --link myMongo:myMongo mongo-express`
> 
> But I'm getting this error:
> 
> ```
> Mongo Express server listening at http://0.0.0.0:8081
> Server is open to allow connections from anyone (0.0.0.0)
> basicAuth credentials are "admin:pass", it is recommended you change this in your config.js!
> 
> /node_modules/mongodb/lib/server.js:265
>         process.nextTick(function() { throw err; })
>                                       ^
> MongoError: failed to connect to server [mongo:27017] on first connect
>     at Pool.<anonymous> (/node_modules/mongodb-core/lib/topologies/server.js:326:35)
>     at emitOne (events.js:116:13)
>     at Pool.emit (events.js:211:7)
>     at Connection.<anonymous> (/node_modules/mongodb-core/lib/connection/pool.js:270:12)
>     at Object.onceWrapper (events.js:317:30)
>     at emitTwo (events.js:126:13)
>     at Connection.emit (events.js:214:7)
>     at Socket.<anonymous> (/node_modules/mongodb-core/lib/connection/connection.js:175:49)
>     at Object.onceWrapper (events.js:315:30)
>     at emitOne (events.js:116:13)
> ```
> Any idea why it is happend? Thanks in advance.

I've fixed that,Actually ,you need set the dockerfile with env variable   ME_CONFIG_MONGODB_SERVER: "mongo_db" , "mongo_db" is container name which you have setted up in mongdb container
