### ISSUE TITLE
Database name allows sequences like %0d, %0a allowing to create names like aaa%0d%0axxx

### ISSUE THREAD

**Issue by bl4de** [mongo-express/mongo-express#400]
Hi,

I was able to create database with following name:
```
aaa%0d%0axxx
```

The problem is that link to this database now contains new line sequence (%0d%0a) and the link now does not allow to go to that database in mongo-express, because it becomes this:

```
http://localhost:8081/db/aaa%0d%0axxx/
```

which in fact resolves into this:

```
http://localhost:8081/db/aaa
```

Not a big deal, but maybe it's something you should be aware of :)

![1](https://user-images.githubusercontent.com/3187617/38506756-a69342f0-3c12-11e8-9240-2b82c041c61b.jpg)

Regards,

Rafal Janicki

**Comment by dozoisch** [comment]
Hmm, we should probably make sure they get url encoded.

**Comment by dozoisch** [comment]
@bl4de better late than never..!
