### ISSUE TITLE
Upgrade mongodb driver to 3.0 for MongoDB 3.6 support

### ISSUE THREAD

**Issue by Hronom** [mongo-express/mongo-express#411]
Please upgrade to [3.0 Driver](https://mongodb.github.io/node-mongodb-native/?jmp=docs&_ga=2.172489123.1430057849.1525679866-319489568.1512160568)

To support [MongoDB 3.6](https://docs.mongodb.com/ecosystem/drivers/driver-compatibility-reference/#node-js-driver-compatibility)

Right now you have ` "mongodb": "2.2.24",`, but according to [matrix compatibility](https://docs.mongodb.com/ecosystem/drivers/driver-compatibility-reference/#node-js-driver-compatibility) it should not break anything. So hopefully it will be a smooth and easy upgrade.

Right now it doesn't work, and I got next:
```
/node_modules/mongodb/lib/server.js:265,
        process.nextTick(function() { throw err; }),
                                      ^,
MongoError: failed to connect to server [mongo:27017] on first connect,
    at Pool.<anonymous> (/node_modules/mongodb-core/lib/topologies/server.js:326:35),
    at emitOne (events.js:116:13),
    at Pool.emit (events.js:211:7),
    at Connection.<anonymous> (/node_modules/mongodb-core/lib/connection/pool.js:270:12),
    at Object.onceWrapper (events.js:317:30),
    at emitTwo (events.js:126:13),
    at Connection.emit (events.js:214:7),
    at Socket.<anonymous> (/node_modules/mongodb-core/lib/connection/connection.js:175:49),
    at Object.onceWrapper (events.js:315:30),
    at emitOne (events.js:116:13),
```

**Comment by wulfsolter** [comment]
If you `npm install mongodb@3.0.8` does it work as intended? If so, can you submit a PR?

**Comment by Hronom** [comment]
Got an error when try to run in docker:
```
npm info it worked if it ends with ok,
npm info using npm@3.8.6,
npm info using node@v5.12.0,
npm info lifecycle mongo-express@0.47.0~prestart: mongo-express@0.47.0,
npm info lifecycle mongo-express@0.47.0~start: mongo-express@0.47.0,
,
> mongo-express@0.47.0 start /app,
> cross-env NODE_ENV=production node app,
,
Welcome to mongo-express,
------------------------,
,
,
/app/lib/db.js:197,
      db.open(processOpenDatabase);,
         ^,
,
TypeError: db.open is not a function,
    at connect (/app/lib/db.js:197:10),
    at router (/app/lib/router.js:21:17),
    at middleware (/app/lib/middleware.js:30:16),
    at Object.<anonymous> (/app/app.js:101:30),
    at Module._compile (module.js:413:34),
    at Object.Module._extensions..js (module.js:422:10),
    at Module.load (module.js:357:32),
    at Function.Module._load (module.js:314:12),
    at Function.Module.runMain (module.js:447:10),
    at startup (node.js:148:18),
,
npm info lifecycle mongo-express@0.47.0~start: Failed to exec start script,
npm ERR! Linux 4.13.0-41-generic,
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start",
npm ERR! node v5.12.0,
npm ERR! npm  v3.8.6,
npm ERR! code ELIFECYCLE,
npm ERR! mongo-express@0.47.0 start: `cross-env NODE_ENV=production node app`,
npm ERR! Exit status 1,,
 ,
npm ERR! Failed at the mongo-express@0.47.0 start script 'cross-env NODE_ENV=production node app'.,
npm ERR! Make sure you have the latest version of node.js and npm installed.,
npm ERR! If you do, this is most likely a problem with the mongo-express package,,
npm ERR! not with npm itself.,
npm ERR! Tell the author that this fails on your system:,
npm ERR!     cross-env NODE_ENV=production node app,
npm ERR! You can get information on how to open an issue for this project with:,
npm ERR!     npm bugs mongo-express,
npm ERR! Or if that isn't available, you can get their info via:,
npm ERR!     npm owner ls mongo-express,
npm ERR! There is likely additional logging output above.,
,
npm ERR! Please include the following file with any support request:,
npm ERR!     /app/npm-debug.log,
```

Please help, I'm not familiar with JavaScript.

**Comment by wulfsolter** [comment]
As the package `mongodb` has gone through a major version change from 2.2.24 to 3.0.8, where things are expected to break, there will probably be some things that break. Please don't say things like "So it should be easy and smooth upgrade." if you don't understand what's involved in an upgrade 😉 

I'd suggest looking at the changelog for `mongodb`, which specifically outlines how `Db.prototype.open
` has been removed, and how to address that. https://github.com/mongodb/node-mongodb-native/blob/master/CHANGES_3.0.0.md

**Comment by Hronom** [comment]
@wulfsolter I say "So it should be easy and smooth upgrade." for one thing - that there support for previous version of mongodb will be available after upgrading, according to the [matrix compatibility](https://docs.mongodb.com/ecosystem/drivers/driver-compatibility-reference/#node-js-driver-compatibility). So you **should** no need to create workaround to support version that you currently support.

The second thing, I have request help from side of developers of mongo express because I'm not familiar with JavaScript - I'm a Java developer. If I was a JavaScript developer I help you with upgrade, but now I'm requesting help from project developers side and community.

**Comment by wulfsolter** [comment]
@Hronom, as it is so "easy and smooth", maybe you could submit a PR? Or maybe you should not say it is "easy and smooth" if you do not know what you are talking about?

**Comment by Hronom** [comment]
@wulfsolter I think for time spended on this discussion about writing someone what he should and what he should not, the JavaScript developer can spend time to something useful in order to submit fix with upgrading to the new version and get many big thanks from the community for pushing this upgrade to the upstream so fast.

**Comment by wulfsolter** [comment]
Ah... A typical п'явка - you want to tell me what to do with my time, but are not smart enough to fix the problem yourself? Surely you could try, you don't have the looks to be this stupid.

**Comment by wulfsolter** [comment]
Thank you @MikeyBurkman, appreciated.

@Hronom,  "easy and smooth" are **not** words you should use especially when this clearly isn't either easy nor smooth. The major version upgrade of the core library used by this project is a huge task. By saying "easy and smooth", you are undermining the value of our efforts. We have donated our time to make this - nobody here is paid, nobody here has a shortage of things to do. We have **given** you this software, do you give back or do you tell us it is bad and cheap? It makes me sick to feel that our efforts are expected for free, or worse, because we give them for free our efforts are also valueless.

Do you work for free? I have to work to earn money to buy fuel and food like everyone else - that you tell me to do something, and to do work for you rather than point out the difficulty of the task, does not make me want to do anything. Do not tell people what to do with their time, if you are asking someone to help you.

If you would like a difficult feature done quickly, maybe you could post an incentive at [BountySource](https://www.bountysource.com/) for someone else to help.

**Comment by dozoisch** [comment]
Cleaned up a bit of the conversation to keep it on topic. There is an open issue, lets focus on it :)

**Comment by JafarAkhondali** [comment]
upgraded to 3.6.2.
