### ISSUE TITLE
GridFS support does not work.

### ISSUE THREAD

**Issue by hryknkgw** [mongo-express/mongo-express#420]
I have started up mongo-express on docker with this command.
`docker run --rm -i -e ME_CONFIG_SITE_GRIDFS_ENABLED="true" -p 8081:8081 --link mongo:mongo mongo-express`

A MongoDB container named 'mongo' have already been started and listened 8081, so mongo-express works well.
But no interface to manage files in GridFS show up on its database page.

There is a set of GridFS related collections (fs.chunks and fs,files) and I confirmed that a file has been uploaded.

**Comment by dozoisch** [comment]
@hryknkgw can you try by changing the config directly? (or providing a config.js with the gridFSEnabled: true) to see if the issue is just the way the variable is passed.

**Comment by hryknkgw** [comment]
I tried providing a config.js with the gridFSEnabled: true to enable GridFS support, but with no luck.
The UI still does not show up.

By adding some debugging code, I have confirmed gridFSEnabled variable passed correctly to `lib/views/database.html` as `settings.gridFSEnabled`.

**Comment by hryknkgw** [comment]
As a result of additional investigation, it turned out that the `grids` variable in `lib/views/database.html` being empty is the cause of the problem.

This bug might introduce  in c23bc79.

Before c23bc79, the `collections` variable was initialized as an object `{}`.
After c23bc79, it is initialized as an array `[]`, though it is treated as an object.
And lodash's clone() doesn't copy any named properties of arrays, so `grids` variable become empty.

**Comment by dozoisch** [comment]
@hryknkgw If you can send a pr that would be much appreciated :)!

**Comment by hryknkgw** [comment]
OK. I will try.
