### ISSUE TITLE
when install in global, i cannot exit it with control+z

### ISSUE THREAD

**Issue by delayhsiao** [mongo-express/mongo-express#427]
as title
i install mongo-express in my mac
and i start mongo-express with command "mongo-express"
when i want to close the program i press the "control+z" it closed
but the process was still in background
i must kill the process when i want to restart the program

**Comment by MikeyBurkman** [comment]
Pressing Ctrl+z in Unix does not close a process. It just puts it in the background. Ctrl+c will close a Unix process. https://askubuntu.com/questions/510811/what-is-the-difference-between-ctrl-z-and-ctrl-c-in-the-terminal

**Comment by delayhsiao** [comment]
@MikeyBurkman i see,thank you
