### ISSUE TITLE
Setting readonly=true in docker compose does not remove delete buttons

### ISSUE THREAD

**Issue by Remco75** [mongo-express/mongo-express#431]
Using the docker-container with docker-compose.yml and setting 
            - ME_CONFIG_OPTIONS_READONLY=true
does not result in a read only site: I still see all the delete options.

Also, the option is not listed at all in the docker-container repo..

**Comment by dozoisch** [comment]
What version of MongoExpress is the container using? ME_CONFIG_OPTIONS_READONLY was added in 0.48.1

**Comment by Remco75** [comment]
well, just put in in the docker compose file and it pulls the latest container. Maybe it wasn't released to the docker repo yet?

**Comment by dozoisch** [comment]
@Remco75 Unfortunately I'm not familiar with the docker repo. Seems like it was merged: https://github.com/mongo-express/mongo-express-docker/pull/14 but I'm not sure if it's in the docker hub and etc.

**Comment by Remco75** [comment]
@dozoisch thnx. I think it was never pushed to the docker hub. I will create issue on that repo

**Comment by Remco75** [comment]
Latest is now pushed, works as expected. Will close issue

**Comment by dozoisch** [comment]
@Remco75 thank you for following up with the docker repo :) !
