### ISSUE TITLE
Is join ($lookup) supported in some way?

### ISSUE THREAD

**Issue by gideoncatz** [mongo-express/mongo-express#438]
I need to do a join between two collections.
I wrote a query with a $lookup, but it doesn't find anything. That is probably because $lookup needs to work within aggregate(), not find().

Is there any plan to support such functionality?

Thanks!

**Comment by dozoisch** [comment]
@gideoncatz I personally don't have the bandwidth for it, I'm more than happy to review a PR if you can do it.
