### ISSUE TITLE
Indexes with partialFilterExpression, show up as [object Object]

### ISSUE THREAD

**Issue by fracmak** [mongo-express/mongo-express#450]
Appears when providing a partialFilterExpression as part of your index, mongo express does not print out the json blob properly, instead prints out [object Object] instead. It would be nice if the JSON object was pretty printed

**Comment by dozoisch** [comment]
@fracmak If you have time to submit a PR that would definitely get this bug fixed faster :)

**Comment by malathi677** [comment]
@dozoisch Have you tried JSON.stringify() for resolving the @fracmak problem.

**Comment by dozoisch** [comment]
@malathi677 I haven't as I haven't had time to investigate this issue at all. I'm more than open to review a PR that would fix this, but I don't have the time myself to do this.
