### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by samames** [mongo-express/mongo-express#467]
Am I correct in my assumption that this would not be installed as a standalone app, but rather on a route such as '/dbadmin', on a production app?

could somebody please explain how to set this up in that way?

Many thanks,
Sam

**Comment by dozoisch** [comment]
@samames you can do both.

To install on routes see https://github.com/mongo-express/mongo-express#usage-express-4-middleware

**Comment by SleepyDeb** [comment]
@rtritto close this 🙏
