### ISSUE TITLE
Can't use ssl-enabled mongo via mongo-express, working in terminal

### ISSUE THREAD

**Issue by ilLuSion-007** [mongo-express/mongo-express#468]
I have mongo v3.4.20 with ssl-enabled and I can login to mongo using terminal via below command i.e.

Terminal Command : mongo --ssl -host hostname --sslCAFile /etc/ssl/ca.pem --sslPEMKeyFile /etc/ssl/key.pem

Files : ca.pem = contains key, crt and key-chain
key.pem = contains key and certificate

I've specified my system hostname above rather than giving direct localhost, moreover on localhost (i.e 127.0.0.1:27017) system without ssl, mongo-express working fine.

In mongo-express with ssl-enabled, I'm facing this error,

```
Welcome to mongo-express
------------------------
Server is open to allow connections from anyone (0.0.0.0)
basicAuth credentials are "admin:pass", it is recommended you change this in your config.js!

/root/mexpress/node_modules/mongodb/lib/server.js:265
        process.nextTick(function() { throw err; })
                                      ^
Error: write EPIPE
    at exports._errnoException (util.js:1050:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:814:14)
```

As of now, I didn't find any information on internet regarding it, so I'm attaching my config.js in .txt version below i.e.

[configjs.txt](https://github.com/mongo-express/mongo-express/files/3191636/configjs.txt)

P.S. - I'm noob in node.js, maybe I've config.js error because I'm able to login via terminal so kindly help. Really appreciated.

**Comment by SleepyDeb** [comment]
Your question doesn't include any detail regarding the configuration you are passing through environment variables 


Feel free to reopen the case.

@rtritto close this

**Comment by rtritto** [comment]
Closing.
@ilLuSion-007 feel free to comment for support.
