### ISSUE TITLE
how did you manage to keep the app bundle so small after docker build

### ISSUE THREAD

**Issue by ionutale** [mongo-express/mongo-express#470]
hi,

i made a simple nodejs app  that is using just express and node-fetch as dependencies and after i containerize it i get 1.08 gb of storage.

while this repo, after creating the container has only 96 mb

how did you manage to obtain such a small container ?

**Comment by taras80** [comment]
See Dockerfile, your answer is there

'''
FROM node:8-slim
....
'''

**Comment by SleepyDeb** [comment]
@rtritto close this
