### ISSUE TITLE
mongo-express doesn't support 'NumberLong' 

### ISSUE THREAD

**Issue by bwitt** [mongo-express/mongo-express#471]
Mongo-express seems to not understand `NumberLong` types:

insert a document through mongo-express:

```
{
    "_id" : NumberLong("379636166684872710"),
    "status" : "lapsed",
    "distance" : NumberLong(0),
}
```

but then try to view the document and it looks like:

```
{
    "_id": 186945536,
    "status": "lapsed",
    "distance": 0,
}
```

i.e. looks like the type `NumberLong` was lost.

Also mongo-express seems to be using the wrong filter when trying to view records record, i.e. assuming you had a pre-existing document with the `"_id" : NumberLong("379636166684872710"),` as above, it would use a filter like

```
`filter: { _id: "379636166684872710" }`,
```

when it should've used
```
filter: { _id: `NumberLong(`"379636166684872710") }
```

**Comment by bwitt** [comment]
perhaps supporting this would be a similar level of effort for https://github.com/mongo-express/mongo-express/issues/415 ?

**Comment by dozoisch** [comment]
@bwitt seems like it would be very similar effort. I don't currently have the bandwidth to take care of this, but I can definitely review PR and cut release if you have some time to tackle it :)

**Comment by ZandercraftGames** [comment]
This is still an issue. My application stores Discord IDs (such as 303016967529562113). When updating the document via mongo-express, it turns it into NumberLong(303016967529562112) and there's no way to get it to be 303016967529562113 unless I use strings which are incompatible with my application's expected data format.
