### ISSUE TITLE
User and password in plain text in the configuration file

### ISSUE THREAD

**Issue by enricolavezzo** [mongo-express/mongo-express#489]
I was able to install and run mongo-express by putting the required data in the config.js file.

The issue I have is that everything (both mongodb and mongo-express credentials) is in plain text, not encrypted in any way, and I think this could be a security issue with a service expose to the web.

Is there any method to avoid this?

**Comment by dozoisch** [comment]
You can customize the config.js tonfir your needs. 

By default you can also pass the information through environment variables, but you could customize it to pass it through any other mean you want.

**Comment by enricolavezzo** [comment]
Thanks for the quick reply!

Do you have some example config.js files to look at?

**Comment by dozoisch** [comment]
@enricolavezzo I don't have examples other than the config.default.js. But that file contains everything needed to connect through environment variables, as well as connecting by reading files.

**Comment by enricolavezzo** [comment]
Ok thanks, I will look better the default file
