### ISSUE TITLE
Delete all documents doesn't work when regex is set

### ISSUE THREAD

**Issue by agolomoodysaada** [mongo-express/mongo-express#493]
When using regex filter, the delete all documents doesn't work and throws a success message along the lines of `undefined documents have been deleted`

**Comment by dozoisch** [comment]
@agolomoodysaada thanks for reporting, if you have time to look into it, it would be much appreciated, I do not currently have the bandwidth to look into it.

**Comment by agolomoodysaada** [comment]
I've looked into it further. Even running a query via mongo shell doesn't work with regex. It seems like a bug in Mongo itself, not so much mongo-express.
