### ISSUE TITLE
Please open a security advisory

### ISSUE THREAD

**Issue by JLLeitschuh** [mongo-express/mongo-express#510]
I've found a security vulnerability I'd like to report. Please open an advisory and add me:

https://github.com/mongo-express/mongo-express/security/advisories

**Comment by dozoisch** [comment]
@JLLeitschuh anything that prevents a direct PR? 

But I'll open one.

**Comment by JLLeitschuh** [comment]
Given the security implications, it's appropriate to have this get fixed privately.
