### ISSUE TITLE
Import fails: "Bad file"

### ISSUE THREAD

**Issue by kuba-orlik** [mongo-express/mongo-express#512]
Importing a collection dump exported from another instance of mongo-express has no result. No error show up, but in the Network Inspector I can see there's a `400` error with the only response content being 

```
Bad file
```

**Comment by moomoo-dev** [comment]
Was this ever fixed ?

**Comment by rtritto** [comment]
> Was this ever fixed ?

@moomoo-dev yes (source: https://github.com/mongo-express/mongo-express/issues/1225#issuecomment-1701077372)
