### ISSUE TITLE
Bump mongodb to version 3.1.13

### ISSUE THREAD

**Issue by omeraha** [mongo-express/mongo-express#513]
Mongo-express@0.53.0 is using mongodb dependency version 2.2.24, which [contains a DoS vulnerability](https://snyk.io/test/npm/mongo-express/0.53.0). This vulnerability was patched in mongodb@3.1.13.

**Comment by Diegoescalonaro** [comment]
Any update about this issue?

**Comment by dozoisch** [comment]
@Diegoescalonaro If this is important for you, we welcome PRs. I don't have the bandwidth to take care of this.

**Comment by rtritto** [comment]
Current version of `mongodb` is greater than 3.1.13, so this issue can be closed.

**Comment by dozoisch** [comment]
Thanks @rtritto
