### ISSUE TITLE
config.js parsing 'false' as string, not boolean

### ISSUE THREAD

**Issue by PathToLife** [mongo-express/mongo-express#520]
I'd love to make a PR to fix, only should others confirm this issue:

Docker via portainer sets env variables as strings.

So strict comparison `===` against boolean variables `false | true` will always fail..

`ME_CONFIG_MONGODB_SSL = 'true'`
`ME_CONFIG_MONGODB_SSLVALIDATE = 'false'`

`typeof ME_CONFIG_MONGODB_SSL === 'string'`
`typeof ME_CONFIG_MONGODB_SSLVALIDATE === 'string'`

When the MongoDB system checks:
`ME_CONFIG_MONGODB_SSL === true`
we'll always resolve false

mongo.ssl as boolean works fine:
![image](https://user-images.githubusercontent.com/12622625/68493086-aa20d700-02b0-11ea-997a-066aa6ac85d8.png)

mongo.ssl as string (as would be parsed from process.env.ME_CONFIG_MONGODB_SSL) errors out
![image](https://user-images.githubusercontent.com/12622625/68493065-9e351500-02b0-11ea-850a-751a2395585b.png)

**Comment by PathToLife** [comment]
![image](https://user-images.githubusercontent.com/12622625/68494040-924a5280-02b2-11ea-8fd7-004c19b27322.png)

Can be done as: 
```js
process.env.ME_CONFIG_MONGODB_ENABLE_ADMIN !== undefined ?
    Boolean(process.env.ME_CONFIG_MONGODB_ENABLE_ADMIN) : false;
```

**Comment by tommck** [comment]
> The config.js file is autistic :)

What the hell?  That's a really shitty comment @PathToLife

**Comment by PathToLife** [comment]
sorry snowflake. i'll make a pr instead
