### ISSUE TITLE
docker build gpg: keyserver receive failed: Cannot assign requested address

### ISSUE THREAD

**Issue by PathToLife** [mongo-express/mongo-express#521]
When running in the root dir:

`docker build -t <imagename>:latest .`

We get:
`gpg: keyserver receive failed: Cannot assign requested address`

Solution:
add this to the docker file:
`RUN echo "disable-ipv6" >> ~/.gnupg/dirmngr.conf`

**Comment by niraizik** [comment]
This can also help:
https://github.com/docker-library/python/pull/335/commits/d483ba96dd4ee66caae2b4b2e85298db6632a649

**Comment by BlackthornYugen** [comment]
Closing as duplicate of #842, but also should be fixed by #804.

**Comment by BlackthornYugen** [comment]
Oh wait, this was to do with IPv6 support... not an issue with the gpg server. @PathToLife can you confirm if this is still an issue?

**Comment by PathToLife** [comment]
Hey thanks for the ping (been a while). Good news it that this gpg function seems to be working.

But I wasn't able to build on `arm64` M1 machine natively (arm64), but seems the gpg step seems to be working.

**Comment by BlackthornYugen** [comment]
@PathToLife I'm on an m1 too! Getting arm64 supported is absolutely high on the list :)

**Comment by mitar** [comment]
You also have to run `apt-key adv --homedir ~/.gnupg --keyserver ...` for workaround to work. [Source](https://github.com/usbarmory/usbarmory-debian-base_image/issues/9#issuecomment-529991242).
