### ISSUE TITLE
Pulse by Slack does not support UTF8 

### ISSUE THREAD

**Issue by aogilvie** [mongo-express/mongo-express#540]
Pulse by email works fine as embedded HTML however the image conversion used to post to Slack shows square where Japanese text should be:

![example](https://user-images.githubusercontent.com/970364/69695284-1e67d100-111f-11ea-88aa-69c05f1601be.png)

metabase 0.33.0 in docker, mongoDB

**Comment by dozoisch** [comment]
hi @aogilvie this seems to be about metabase and not mongo-express.

**Comment by aogilvie** [comment]
Sorry. My bad.
