### ISSUE TITLE
Pluse formatting does not take into account Question column formatting rules 

### ISSUE THREAD

**Issue by aogilvie** [mongo-express/mongo-express#541]
- Create a question
- Change the column formatting (for example column name, or format the date YYYY/MM/DD)
- Create pulse
- Test send pulse

changes are not applied to pulse data attachments (Slack or Email).

metabase 0.33.0 in docker, mongoDB

**Comment by dozoisch** [comment]
hi @aogilvie this seems to be about metabase and not mongo-express.

**Comment by aogilvie** [comment]
Sorry. My bad.
