### ISSUE TITLE
Pulse column width does not format correctly

### ISSUE THREAD

**Issue by aogilvie** [mongo-express/mongo-express#542]
See below; date is cut off even though the field contains hour and mins.

Question in Metabase:
![example2](https://user-images.githubusercontent.com/970364/69695516-ffb60a00-111f-11ea-95f9-c27bb5130908.png)

Pulse in Slack:
![example](https://user-images.githubusercontent.com/970364/69695471-dd23f100-111f-11ea-8d22-cfd5dafcc5fe.png)

metabase 0.33.0 in docker, mongoDB

**Comment by dozoisch** [comment]
hi @aogilvie this seems to be about metabase and not mongo-express.

**Comment by aogilvie** [comment]
Sorry. My bad.
