### ISSUE TITLE
Feature Request: Question column formatting, remove day, month, year

### ISSUE THREAD

**Issue by aogilvie** [mongo-express/mongo-express#543]
Currently it is possible to "Show the time" to Off.
Why not add "Date separators" to Off.

![example](https://user-images.githubusercontent.com/970364/69695594-3d1a9780-1120-11ea-8b25-b7a975868ec9.png)

metabase 0.33.0 in docker, mongoDB

**Comment by dozoisch** [comment]
hi @aogilvie this seems to be about metabase and not mongo-express.

**Comment by aogilvie** [comment]
Sorry. My bad.
