### ISSUE TITLE
Releases on dockerhub are outdated

### ISSUE THREAD

**Issue by GenericHelperUtilCommonLib** [mongo-express/mongo-express#549]
Hi,

The latest available container of mongo-express on [dockerhub](https://hub.docker.com/_/mongo-express) is version 0.49 from Jul 9, 2018.

The current version in github is 0.54, and has a lot of features we would like to use. 

Could you please push a new release on the dockerhub?

**Comment by dozoisch** [comment]
@GenericHelperUtilCommonLib unfortunately, I don't have write access to the dockerhub. Feel free to open an issue with https://github.com/mongo-express/mongo-express-docker/issues

**Comment by GenericHelperUtilCommonLib** [comment]
> @GenericHelperUtilCommonLib unfortunately, I don't have write access to the dockerhub. Feel free to open an issue with https://github.com/mongo-express/mongo-express-docker/issues

I see, thank you for your reply.  I will do that then.
