### ISSUE TITLE
Document Not Found when I want to show the details of a document

### ISSUE THREAD

**Issue by mawx** [mongo-express/mongo-express#566]
Hello,

This error occurs when I use the 0.54.0 version of mongo-express in the 0.54.0 containerized image provided by docker-hub (https://hub.docker.com/_/mongo-express), in a kubernetes environment.

When I'm in the page "viewing collection ..." and when I click on a document, in order to retrieve its details, I get a 404 not found:
![image](https://user-images.githubusercontent.com/6087857/80393756-3e0f4b00-88b1-11ea-9e24-1072e4a62e1c.png)

Moreover I can see that in the url, the document name is incomplete:
`https://my-server-name/"5e733f1204169d0588000009"`

I only have the document-id at the end, I should also have the document-name. When I modify the url by adding the document name, I retrieve the details correctly:
`https://my-server-name/db/db-name/contextual_placement/"5e733f1204169d0588000009"`

After digging a while it seems that this problem comes from the js function in collection.js file:
```
window.loadDocument = function (url) {
   const selection = window.getSelection().toString();
   if (selection === '') {
      location.href = url;
   }
};
```

I tried to modify it by adding the current location before the url of the document I want to show, and the problem seems to be resolved for me:

```
window.loadDocument = function (url) {
   const selection = window.getSelection().toString();
   if (selection === '') {
      location.href = location.href + '/' + url;
   }
};
```

I hope you'll have enough details to reproduce this :)

By the way, thank you for your great work !

**Comment by shakaran** [comment]
Closing as fixed
