### ISSUE TITLE
"UnhandledPromiseRejectionWarning: MongoNetworkError: failed to connect to server [undefined:27017] on first connect [Error: getaddrinfo ENOTFOUND undefined"

### ISSUE THREAD

**Issue by tianon** [mongo-express/mongo-express#581]
Hi!  When trying to update https://github.com/mongo-express/mongo-express-docker to 1.0.0-alpha.1, I can't seem to run `mongo-express` successfully no matter how I install version 1.0.0-alpha.1, and I hope it's because there's something obvious I'm doing wrong.

No matter what I do (removing all environment variables, installing via `yarn` vs `npm`, etc etc etc), I'm getting the following error/backtrace:

```console
No custom config.js found, loading config.default.js
Welcome to mongo-express
------------------------


(node:1) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
Could not connect to database at index "0"
(node:1) UnhandledPromiseRejectionWarning: MongoNetworkError: failed to connect to server [undefined:27017] on first connect [Error: getaddrinfo ENOTFOUND undefined
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26) {
  name: 'MongoNetworkError'
}]
    at Pool.<anonymous> (/opt/mongo-express/node_modules/mongodb/lib/core/topologies/server.js:438:11)
    at Pool.emit (events.js:315:20)
    at /opt/mongo-express/node_modules/mongodb/lib/core/connection/pool.js:562:14
    at /opt/mongo-express/node_modules/mongodb/lib/core/connection/pool.js:995:11
    at /opt/mongo-express/node_modules/mongodb/lib/core/connection/connect.js:31:7
    at callback (/opt/mongo-express/node_modules/mongodb/lib/core/connection/connect.js:264:5)
    at Socket.<anonymous> (/opt/mongo-express/node_modules/mongodb/lib/core/connection/connect.js:294:7)
    at Object.onceWrapper (events.js:422:26)
    at Socket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I'm not sure whether the displayed warnings are the cause of the failure (the server exits immediately after those warnings are displayed) or whether there's something else causing the server to exit. :sweat:  I'm *guessing* the line that's hiding in the middle there (`Could not connect to database at index "0"`) is the real error but I'm not certain.

The easiest way to reproduce is via a `Dockerfile` like the following:

```dockerfile
FROM node:12-buster-slim

RUN set -eux; \
	apt-get update; \
	apt-get install -y --no-install-recommends tini; \
	rm -rf /var/lib/apt/lists/*

EXPOSE 8081

# override some config defaults with values that will work better for docker
ENV ME_CONFIG_MONGODB_SERVER="mongo" \
    ME_CONFIG_MONGODB_ENABLE_ADMIN="true" \
    VCAP_APP_HOST="0.0.0.0"

WORKDIR /opt/mongo-express
COPY . .
RUN yarn install
RUN yarn run build

CMD ["tini", "--", "yarn", "run", "start"]
```

Like I said, I've tried various things like installing directly via `npm`/`yarn`, removing all environment variables, setting `ME_CONFIG_MONGODB_URL`, etc, and nothing allows me to start the server successfully (it always exits with this same output). :disappointed:

Happy to do more testing/debugging, with a little guidance! :+1:

**Comment by tianon** [comment]
As an interesting update, if I supply an appropriate `--url` on the server command-line, it works!  However, just using `--host` does not (and environment variables also do not).

I've also tried copying `config.default.js` over to `config.js` as per the README, but it doesn't change anything (which isn't exactly unexpected, given that it clearly states it's loading `config.default.js` when `config.js` doesn't exist :sweat_smile:).

**Comment by ccandreva** [comment]
I have this same issue with a copy installed via npm

**Comment by knickers** [comment]
I've been trying to build this. The first time I built and ran it, after the mongo-express error, there was a mongo output that said:
```
MongoDB init process complete; ready for start up.
```
This ouput only happened the first time, it has not since.

So I thought perhaps the wait loop `wait_tcp_port` in mongo-express-docker [docker-entrypoint.sh](https://github.com/mongo-express/mongo-express-docker/blob/master/docker-entrypoint.sh) could make a difference. But I've been unsuccessful in trying to integrate the entrypoint script.

Are there any maintainers or contributors who know `node` a little better who can help decipher this error?

**Comment by dozoisch** [comment]
So 1.0.0 changed the way the connection module worked. I tried to make it as backward compatible as possible with before but possible it's not 100%.

From memory, ME_CONFIG_MONGODB_URL should work. I'll take a look at the base config but definitely passing a URL instead of host/port is better with 1.0 because if I receive anything else than a URL, I try to rebuild a url from the rest (which is where the bug might happen).

**Comment by dozoisch** [comment]
@knickers I'd be down that we clean up all the docker variables for 1.0 to use a single connection string and get rid of the 4-5 other ones. 

If I remember (been a while 😅 ) I support passing an array for "mongodb" to connect to multiple db so we could look into supporting that as well

**Comment by rayfoss** [comment]
I also get the same error with a URL! using latest npm alpha1 with npx, no cache.

`npx mongo-express -a -U "mongodb://user:password@c-shard0,c-shard1,c-shard2/colletion?ssl=true&replicaSet=shard&authSource=admin"`
```
(node:1778106) UnhandledPromiseRejectionWarning: MongoNetworkError: failed to connect to server [c-shard0-00-msobk.mongodb.net:27099] on first connect [MongoNetworkError: connection 5 to c-shard0-00-msobk.mongodb.net:27099 closed
    at Socket.<anonymous> (/home/u/.npm/_npx/1778106/lib/node_modules/mongo-express/node_modules/mongodb/lib/core/connection/connection.js:440:9)
    at Object.onceWrapper (events.js:422:26)
    at Socket.emit (events.js:315:20)
    at TCP.<anonymous> (net.js:674:12)]
    at Pool.<anonymous> (/home/u/.npm/_npx/1778106/lib/node_modules/mongo-express/node_modules/mongodb/lib/core/topologies/server.js:438:11)
    at Pool.emit (events.js:315:20)
    at /home/u/.npm/_npx/1778106/lib/node_modules/mongo-express/node_modules/mongodb/lib/core/connection/pool.js:562:14
    at /home/u/.npm/_npx/1778106/lib/node_modules/mongo-express/node_modules/mongodb/lib/core/connection/pool.js:1009:9
    at callback (/home/u/.npm/_npx/1778106/lib/node_modules/mongo-express/node_modules/mongodb/lib/core/connection/connect.js:75:5)
    at /home/u/.npm/_npx/1778106/lib/node_modules/mongo-express/node_modules/mongodb/lib/core/connection/connect.js:101:9
    at _callback (/home/u/.npm/_npx/1778106/lib/node_modules/mongo-express/node_modules/mongodb/lib/core/connection/connection.js:329:7)
    at Connection.errorHandler (/home/u/.npm/_npx/1778106/lib/node_modules/mongo-express/node_modules/mongodb/lib/core/connection/connection.js:344:7)
    at Object.onceWrapper (events.js:422:26)
    at Connection.emit (events.js:315:20)
    at Socket.<anonymous> (/home/u/.npm/_npx/1778106/lib/node_modules/mongo-express/node_modules/mongodb/lib/core/connection/connection.js:438:12)
    at Object.onceWrapper (events.js:422:26)
    at Socket.emit (events.js:315:20)
    at TCP.<anonymous> (net.js:674:12)
```

**Comment by dozoisch** [comment]
@rayfoss unfortunately if we publish as alpha no one will  test. 

The goal with the 1.0 release is to try to move the backbone to the native driver as much as possible to avoid issues that were happening where as using the driver would've worked. 

This project has to depend on the community to help with testing as it has no dedicated funding. I'm sorry you are having issues but Atlas is not something I personally use therefore whether we publish as alpha or not, these issues wouldn't be picked up.

If you try to connecting using `require("mongodb").connect(url, options, console.log.bind(console)` what happens? Does it connect?

---


@knickers I'm down to deprecate the host and other parameters.. to be honest, these create issues more than they help. Only allowing to pass a url seems like it would simplify things in the future.
