### ISSUE TITLE
Any plan to improve UI?

### ISSUE THREAD

**Issue by JafarAkhondali** [mongo-express/mongo-express#599]
Hello there,
Are you planning on improving the UI? how about using a modern framework like Vue, or using SPA?
Please clarify on wihch things would be welcomed in this project.

Thanks for the useful product :+1:

**Comment by dozoisch** [comment]
Hi Jafar, 

Right now, there is no plan for UI overhauls as I don't have any bandwidth to work on such endeavors.

I'm not against PRs to do a revamp and improve things however I don't have time to lead that effort myself.

I'm personally in the React ecosystem, so have a preference towards that as it makes it easier for me to review/maintain, but am open to see this project take another direction, especially if people are willing to step in for maintenance of it.

**Comment by JafarAkhondali** [comment]
Thanks @dozoisch 
We might want to work on it and make the backend API based + Vuejs(SPA) for the front end, not 100% sure but this is the best scenario for us. If there are any guidelines for this project or disagreements, please mention it :bow:

**Comment by dozoisch** [comment]
I think that's fine. I would only be careful with project size. Right now the UI is very minimal in terms of code while still having a lot of the needed feature. I'm all for SPA would just be careful it if means having 10x more to maintain vs just updating the UI visually to make it more compelling.

Other than that, that's fine with me.
