### ISSUE TITLE
Pagination with filters has an error

### ISSUE THREAD

**Issue by sokolovvs** [mongo-express/mongo-express#645]
Pagination with filters has an error.

Please, see these screenshots:

http://joxi.ru/BA0Xn5aCpD1DJA
http://joxi.ru/KAg67gETKd5LV2

**Comment by JafarAkhondali** [comment]
Hello @sokolovvs ,
On latest version of npm it should be fixed now. We're waiting for publish on dockerhub.
Feel free to reopen this issue if still exists.
