### ISSUE TITLE
Latest docker image is broken

### ISSUE THREAD

**Issue by omeid** [mongo-express/mongo-express#649]
The latest image is from before auth db handling was [fixed](https://github.com/mongo-express/mongo-express/commit/440f0e5553656a9336a07639b86e6984d27d7d94).

For some reason version 0.50 through to 0.54 is also missing from docker hub which means there is no working recent version, since 0.49 is a year old!

**Comment by rtritto** [comment]
Images in Docker hub are updated with latest versions, so this issue can be closed.
