### ISSUE TITLE
MongoNetworkError: failed to connect to server [localhost:27017] on first connect [{ MongoError: Authentication failed.

### ISSUE THREAD

**Issue by Braedencraig** [mongo-express/mongo-express#655]
Cannot authenticate my db even though my credentials are correct. Have tried almost everything under the sun. Am running BIG SUR. Could this be the issue?

**Comment by datduyng** [comment]
I am running on a window and facing the same problem.

**Comment by KrizaLee** [comment]
Modify:
https://github.com/mongo-express/mongo-express/blob/38e583b520262e9c6762f06c8b374b1dddc7ab9d/config.default.js#L77-L78
To:
```JavaScript
    username: getFileEnv(adminUsername) || getFileEnv(dbAuthUsername) || mongo.username,
    password: getFileEnv(adminPassword) || getFileEnv(dbAuthPassword) || mongo.password,
```
When the MongoDB username and password are empty, the `username` will default to `dbAuthUsername`, and the `password` will default to `dbAuthPassword`

https://github.com/mongo-express/mongo-express/blob/38e583b520262e9c6762f06c8b374b1dddc7ab9d/config.default.js#L25-L26
So will cause an exception: `MongoError: Authentication failed.`
