### ISSUE TITLE
Environment option "no delete" is ignored

### ISSUE THREAD

**Issue by nbossard** [mongo-express/mongo-express#657]
Hello I have configured latest version (0.54) of mongo express with environment variable : 

ME_CONFIG_OPTIONS_NO_DELETE: 'true'

But it seems this option is ignored.

Looking at : 

https://github.com/mongo-express/mongo-express/blob/440f0e5553656a9336a07639b86e6984d27d7d94/config.default.js#L203

Found : 
>    // noDelete: if noDelete is set to true, we won't show delete buttons
 >   noDelete: process.env.ME_CONFIG_OPTIONS_NO_DELETE || false,

Shouldn't it be something like  : 
>    noDelete: process.env. ME_CONFIG_OPTIONS_NO_DELETE
>      ? process.env. ME_CONFIG_OPTIONS_NO_DELETE.toLowerCase() === 'true'
>      : false,

**Comment by JafarAkhondali** [comment]
Hello @nbossard 
I've tested env variables and it worked correctly (at least on latest version). Maybe there was a mistake when you set the env variables.
The code is also fine.
