### ISSUE TITLE
Unable to delete doc with UUID as _id

### ISSUE THREAD

**Issue by Xairoo** [mongo-express/mongo-express#668]
Document not found appears when I try to delete a doc that uses UUID instead of ObjectId.

I use UUIDs because it looks like a random ID, so the user cannot guess easily the next id.

**Comment by JafarAkhondali** [comment]
Hello @Xairoo 
Can you provide sample of created documents and your remove query?

**Comment by Xairoo** [comment]
Hello @JafarAkhondali 

```
{
    _id: UUID("ea0a23e49fd143ddab5a9576ca1dd0f6"),
    foo: 'bar'
}
```
_id is shown as `6goj5J/RQ92rWpV2yh3Q9g==` in the collections view.
This will result in this POST request: `http://localhost:8082/db/foo/test/%226goj5J%2FRQ92rWpV2yh3Q9g%3D%3D%22?skip=0&key=&value=&type=&query=&projection=`

Viewing the document works: `http://localhost:8082/db/foo/test/%226goj5J%2FRQ92rWpV2yh3Q9g%3D%3D%22?subtype=4`
Only the title should be converted to the UUID like in the JSON view / code mirror.

**Comment by denebgarza** [comment]
Ran into the same issue and opened a PR with a fix https://github.com/mongo-express/mongo-express/pull/704

@Xairoo if you want a temp workaround, you can click on the document and use the delete button in the document view. It works there, but not in the collection view.

**Comment by BlackthornYugen** [comment]
@denebgarza thanks for the PR :)
