### ISSUE TITLE
`gpg: keyserver receive failed: No name` when building docker container

### ISSUE THREAD

**Issue by YoshieraHuang** [mongo-express/mongo-express#803]
Hello. I failed to build the docker image due to the `gpg: keyserver receive failed: No name` error during gpg verification. I saw a PR #575 try to fix it by removing the verification but it was declined. As https://github.com/nodejs/docker-node/issues/1500 said, the actual reason is the `sks-keyservers.net` is never available to verify gpg keys. `keyserver.ubuntu.com` and `keys.opengpg.org` are good alternatives. I succeed to pass the validataion with these two servers.

**Comment by BlackthornYugen** [comment]
Resolved by #804
