### ISSUE TITLE
[error] npm install -g mongo-express failed

### ISSUE THREAD

**Issue by flameleo11** [mongo-express/mongo-express#810]
mi@redmi:~/tmp$ npm install -g mongo-express
npm WARN deprecated express-fileupload@0.4.0: Please upgrade express-fileupload to version 1.1.8+ due to a security vulnerability with the parseNested option
npm WARN deprecated uuid@2.0.3: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
/home/mi/.nvm/versions/node/v14.18.1/bin/mongo-express -> /home/mi/.nvm/versions/node/v14.18.1/lib/node_modules/mongo-express/app.js

> mongo-express@1.0.0-alpha.4 postinstall /home/mi/.nvm/versions/node/v14.18.1/lib/node_modules/mongo-express
> patch-package

patch-package 6.4.7
Applying patches...

**ERROR** Failed to apply patch for package mongodb-query-parser at path
  
    node_modules/mongodb-query-parser

  This error was caused because mongodb-query-parser has changed since you
  made the patch file for it. This introduced conflicts with your patch,
  just like a merge conflict in Git when separate incompatible changes are
  made to the same piece of code.

  Maybe this means your patch file is no longer necessary, in which case
  hooray! Just delete it!

  Otherwise, you need to generate a new patch file.

  To generate a new one, just repeat the steps you made to generate the first
  one.

  i.e. manually make the appropriate file changes, then run 

    patch-package mongodb-query-parser

  Info:
    Patch file: patches/mongodb-query-parser+2.1.2.patch
    Patch was made for version: 2.1.2
    Installed version: 2.4.3

---
patch-package finished with 1 error(s).
npm WARN notsup Unsupported engine for got@5.7.1: wanted: {"node":">=0.10.0 <7"} (current: {"node":"14.18.1","npm":"6.14.15"})
npm WARN notsup Not compatible with your version of node/npm: got@5.7.1

+ mongo-express@1.0.0-alpha.4
added 316 packages from 197 contributors in 8.14s
mi@redmi:~/tmp$ mongo-express --url mongodb://127.0.0.1:27017
No custom config.js found, loading config.default.js
Welcome to mongo-express
------------------------

(node:133931) [MONGODB DRIVER] Warning: Current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
(Use `node --trace-warnings ...` to show where the warning was created)
Mongo Express server listening at http://localhost:8081
basicAuth credentials are "admin:pass", it is recommended you change this in your config.js!
^C

**Comment by rtritto** [comment]
Fixed with #907

**Comment by veptune** [comment]
Hello.
Same issue here. It is just impossible to install mongo-express via NPM anymore : 

MacBook-Air-de-nicolas:~ nicolas$ npm install -g mongo-express
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "patch:": patch:mongodb-query-parser@npm%3A2.4.6#~/.yarn/patches/mongodb-query-parser-npm-2.4.6-234abad2fc.patch

**Comment by Faizahamed-dev** [comment]
Hi all, 

kindly help me to fix this issue.

npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "patch:": patch:mongodb-query-parser@npm%3A2.4.6#~/.yarn/patches/mongodb-query-parser-npm-2.4.6-234abad2fc.patch

npm ERR! A complete log of this run can be found in: /home/faiz_sheik_ahamed/.npm/_logs/2023-04-27T02_01_58_558Z-debug-0.log

**Comment by stefexec** [comment]
✘ stefan@wheatley  ~  npm install mongo-express 
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "patch:": patch:mongodb-query-parser@npm%3A2.4.6#~/.yarn/patches/mongodb-query-parser-npm-2.4.6-234abad2fc.patch

npm ERR! A complete log of this run can be found in: /home/stefan/.npm/_logs/2023-05-05T09_07_17_087Z-debug-0.log
 ✘ stefan@wheatley  ~ 

**Comment by KamranV21** [comment]
You can try to install the previous version of mongo-express:
`npm i -g mongo-express@1.0.0`

**Comment by Aineah-Simiyu** [comment]
@KamranV21 Thanks it works by downgrading the installation package!
