### ISSUE TITLE
ME_CONFIG_MONGODB_ENABLE_ADMIN=true no longer valid

### ISSUE THREAD

**Issue by manassingh2611** [mongo-express/mongo-express#822]
Image: mongo-express:0.49.0
![1](https://user-images.githubusercontent.com/39790333/148828572-ce7acd54-ab89-4a62-a001-9420d4db6ca0.png)

Image: mongo-express:latest
![2](https://user-images.githubusercontent.com/39790333/148827881-429172ce-9083-426e-a378-748959a00190.png)

**Comment by sq4cvh** [comment]
I confirm, I test on docker 0.54.0 images is OK, the latest is wrong, 1.0.0-alpha.4 is also wrong

**Comment by kingmanas** [comment]
@sq4cvh I use [mongo-compass](https://www.mongodb.com/products/compass) now, it works fine.

**Comment by rtritto** [comment]
It's fixed with https://github.com/mongo-express/mongo-express/pull/792
Wating for the new release and Docker image.
As alternative, you can start it locally or create a Dockerbuild using this repository.

**Comment by rtritto** [comment]
Will be fixed with https://github.com/mongo-express/mongo-express-docker/pull/82

**Comment by shakaran** [comment]
Closing this as fixed since #82 is merged. Reopen if still present
