### ISSUE TITLE
is this project dead?

### ISSUE THREAD

**Issue by bitsofinfo** [mongo-express/mongo-express#824]
is this project dead? any actively maintained forks? says last release 2016

**Comment by Roemer** [comment]
I think one main distribution ways is now Docker Hub. See https://hub.docker.com/_/mongo-express/?tab=tags&page=1 for more recent Docker Images (latest stable seems to be 0.54 from October, 2021). So it is at least not completely dead although there are tons of PRs with dependency / security updates pending which should be processed at least.

**Comment by shakaran** [comment]
I try to reach the mantainers for offer my help to contributions and review pull requests. Lets see if we can move the project with more updates soon

**Comment by BlackthornYugen** [comment]
@dozoisch does it make sense to do an updated npm & docker release now or should we wait until we finish updating the remaining vulnerabilities?

**Comment by shakaran** [comment]
> @dozoisch does it make sense to do an updated npm & docker release now or should we wait until we finish updating the remaining vulnerabilities?

You can always release alphas and we can snapshot the master branch in small iterations. For example one alpha per week, so we have points in time to test it

**Comment by shakaran** [comment]
Closing this as fixed, since all the team have released and started again to merge pull request and evolve the code ;)
