### ISSUE TITLE
Regression: cannot use docker swarm secrets in > 0.54.0

### ISSUE THREAD

**Issue by alexrudd2** [mongo-express/mongo-express#836]
With the deprecation of `ME_CONFIG_MONGODB_SERVER`, `ME_CONFIG_MONGODB_ADMINUSERNAME`, etc. in favor of only `ME_CONFIG_MONGODB_URL`, the corresponding `_FILE` options were also removed.

This makes it impossible to use Docker Swarm secrets, which was added in https://github.com/mongo-express/mongo-express/issues/363
```
     - ME_CONFIG_MONGODB_ADMINUSERNAME=root
     - ME_CONFIG_MONGODB_ADMINPASSWORD_FILE=/run/secrets/MONGO_ROOT_PASSWORD
     - ME_CONFIG_MONGODB_SERVER=mongo_mongo-a,mongo_mongo-b
 ```

This only workaround I can find is reverting to `0.54.0`

**Comment by BlackthornYugen** [comment]
When I look at [config.default.js](https://github.com/mongo-express/mongo-express/blob/73875b3d9ed1516febf30475ab06548c13b5b38a/config.default.js#L45-L55), it appears that the _FILE options are currently supported, it even prefers the file var over the non-file var if both are provided:

```js
function getFileEnv(envVariable) {
  const origVar = process.env[envVariable];
  const fileVar = process.env[envVariable + '_FILE'];
  if (fileVar) {
    const file = getFile(fileVar);
    if (file) {
      return file.toString().split(/\r?\n/)[0].trim();
    }
  }
  return origVar;
}
```

@alexrudd2 can you confirm if this is still an issue?

**Comment by alexrudd2** [comment]
> @alexrudd2 can you confirm if this is still an issue?

Yes, still a crashloop when I change the image with working config from 
`mongo-express:0.54.0@sha256:6bc39d97568da612e43a677983fa570eb3e7f9babd00e41d904308ba4bd13fc5` 
to `mongo-express:latest`

**Comment by BlackthornYugen** [comment]
I haven't been able to actually test loading a variable from a file yet, but when I look at the config, it appears that it should prefer file vars over environment vars

```bash
docker run --rm -it \
  mongo-express:0.54.0@sha256:6bc39d97568da612e43a677983fa570eb3e7f9babd00e41d904308ba4bd13fc5 \
    grep -n -m1 -A4 getFileEnv config.js
```

```
41:function getFileEnv(envVariable) {
42-  const origVar = process.env[envVariable];
43-  const fileVar = process.env[envVariable + '_FILE'];
44-  if (fileVar) {
45-    const file = getFile(fileVar);
```
