### ISSUE TITLE
Feature Request: Unauthenticated health check

### ISSUE THREAD

**Issue by masus04** [mongo-express/mongo-express#849]
For certain deployments, e.g. Kubernetes with CGE Load Balancers, each pod is required to provide an unauthenticated health check route. This route ("/" by default, but I think it can be configured) should responds with status code `200 OK` when the service is running properly.

Currently, `mongo-express` only supports this requirement if basic auth is disabled, which then leaves it completely unauthenticated.

I propose an additional parameter `ME_CONFIG_HEALTH_CHECK_PATH`, which creates an unauthenticated route that simply returns `200 OK` when called. The fact that the route can be called should suffice as a health check, although more elaborate ones could also be implemented.

Ideally this route should work in combination with `ME_CONFIG_SITE_BASEURL`, such that the following scenario would be possible:

- `ME_CONFIG_SITE_BASEURL = "/express"` -> The mongo-express UI is served on "/express"
- `ME_CONFIG_HEALTH_CHECK_PATH = "/"` -> Health checks can be run on "/"

**Comment by shakaran** [comment]
@masus04 would you like to propose a draft or pull request for this feature?

**Comment by masus04** [comment]
I'm not familiar with the project, so I'm not sure I can create a PR in a reasonable time frame.

But generally i think this could be implemented by simply providing an endpoint `/status` or `/health-check` which returns a status `200 OK` if everything is ok plus potentially some other interesting information. It would have to be unauthenticated though. And I'm not sure if this should be available by default or only when configured to do so.
