### ISSUE TITLE
Update swig-templates to free-swig to fix security vulnerabilities

### ISSUE THREAD

**Issue by OOCAZ** [mongo-express/mongo-express#959]
Trying to get involved and contribute in order to get this to be all that is can be. I pulled a local copy and found that we can remove all of the current security vulnerabilities recognized by node if we simply change packages from the depreciated swig-template to free-swig. The usage and implementation is the same, we just need to change the name of the import in middleware.js and appear to have fixed it.

Let me know what steps I can take next to contribute.

Have a great day!

**Comment by OOCAZ** [comment]
Additional note all unit tests passed when this change was made.

**Comment by OOCAZ** [comment]
created pull request with changes

**Comment by rtritto** [comment]
Fixed with #960
