### ISSUE TITLE
New free-swig version needed on NPM

### ISSUE THREAD

**Issue by OOCAZ** [mongo-express/mongo-express#964]
We need a new version on npm with the resolved swig-templates to free-swig. I don't know what that takes to do, but I am more than happy to help with the process if I can.

**Comment by OOCAZ** [comment]
Once we get a new version published then we can do some in depth vulnerability scans and figure out if any other major dependency updates are needed.

**Comment by rtritto** [comment]
@OOCAZ Version 1.0.1 was released.
