### ISSUE TITLE
Cannot turn off basicAuth

### ISSUE THREAD

**Issue by radokristof** [mongo-express/mongo-express#969]
From v1.0.0 I can't turn off basicAuth.

Setting username as empty in the docker-compose file:
```
  - ME_CONFIG_BASICAUTH_USERNAME=""
```

And it still asks for username/password, but nothing is accepted. Deleting this env, will fall back to default 'admin:pass', but I don't want to have basicAuth, because I access mongo-express through a reverse proxy (which has its own authentication and ssl)

**Comment by BlackthornYugen** [comment]
Docker seems to ignore setting vars as empty strings...
 
## Empty string with docker cli

![image](https://user-images.githubusercontent.com/3138467/190530056-38533515-d7e3-4c1c-a617-7fb5de2c7502.png)

## Empty string with docker compose

![image](https://user-images.githubusercontent.com/3138467/190530303-276a8dca-5d5b-440d-ba80-a7ef0d88735e.png)

**Comment by BlackthornYugen** [comment]
A fix might be to allow users to disable basic auth with ME_CONFIG_BASICAUTH=false like this: 

```diff
diff --git a/config.default.js b/config.default.js
index 2762ca4..47ed4fe 100644
--- a/config.default.js
+++ b/config.default.js
@@ -20,6 +20,7 @@ if (process.env.VCAP_SERVICES) {
   }
 }
 
+const basicAuth = 'ME_CONFIG_BASICAUTH';
 const basicAuthUsername = 'ME_CONFIG_BASICAUTH_USERNAME';
 const basicAuthPassword = 'ME_CONFIG_BASICAUTH_PASSWORD';
 const adminUsername = 'ME_CONFIG_MONGODB_ADMINUSERNAME';
@@ -134,7 +135,7 @@ export default {
   // set useBasicAuth to true if you want to authenticate mongo-express logins
   // if admin is false, the basicAuthInfo list below will be ignored
   // this will be true unless ME_CONFIG_BASICAUTH_USERNAME is set and is the empty string
-  useBasicAuth: getFileEnv(basicAuthUsername) !== '',
+  useBasicAuth: getBoolean(basicAuth, getFileEnv(basicAuthUsername) !== ''),
 
   basicAuth: {
     username: getFileEnv(basicAuthUsername) || 'admin',
```

**Comment by radokristof** [comment]
@BlackthornYugen would be great, thanks!
